/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigClamavUpdateClamavSectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigClamavUpdateClamavSectionRequest{}

// ConfigClamavUpdateClamavSectionRequest struct for ConfigClamavUpdateClamavSectionRequest
type ConfigClamavUpdateClamavSectionRequest struct {

	// Whether to mark encrypted archives and documents as heuristic virus match. A match does not necessarily result in an immediate block, it just raises the Spam Score by 'clamav_heuristic_score'.
	Archiveblockencrypted *PmgBoolean `json:"archiveblockencrypted,omitempty"`

	// Number of files to be scanned within an archive, a document, or any other kind of container. Warning: disabling this limit or setting it too high may result in severe damage to the system.
	Archivemaxfiles *int64 `json:"archivemaxfiles,omitempty"`

	// Nested archives are scanned recursively, e.g. if a ZIP archive contains a TAR  file,  all files within it will also be scanned. This options specifies how deeply the process should be continued. Warning: setting this limit too high may result in severe damage to the system.
	Archivemaxrec *int64 `json:"archivemaxrec,omitempty"`

	// Files larger than this limit (in bytes) won't be scanned.
	Archivemaxsize *int64 `json:"archivemaxsize,omitempty"`

	// ClamAV database mirror server.
	Dbmirror *string `json:"dbmirror,omitempty"`

	// A list of settings you want to delete.
	Delete *string `json:"delete,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// This option sets the lowest number of Credit Card or Social Security numbers found in a file to generate a detect.
	Maxcccount *int64 `json:"maxcccount,omitempty"`

	// Sets the maximum amount of data (in bytes) to be scanned for each input file.
	Maxscansize *int64 `json:"maxscansize,omitempty"`

	// Enables ScriptedUpdates (incremental download of signatures)
	Scriptedupdates *PmgBoolean `json:"scriptedupdates,omitempty"`

}

// NewConfigClamavUpdateClamavSectionRequest instantiates a new ConfigClamavUpdateClamavSectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigClamavUpdateClamavSectionRequest() *ConfigClamavUpdateClamavSectionRequest {
	this := ConfigClamavUpdateClamavSectionRequest{}
	var archiveblockencrypted PmgBoolean = PMGBOOLEAN__0
	this.Archiveblockencrypted = &archiveblockencrypted
	var archivemaxfiles int64 = 1000
	this.Archivemaxfiles = &archivemaxfiles
	var archivemaxrec int64 = 5
	this.Archivemaxrec = &archivemaxrec
	var archivemaxsize int64 = 25000000
	this.Archivemaxsize = &archivemaxsize
	var dbmirror string = "database.clamav.net"
	this.Dbmirror = &dbmirror
	var maxcccount int64 = 0
	this.Maxcccount = &maxcccount
	var maxscansize int64 = 100000000
	this.Maxscansize = &maxscansize
	var scriptedupdates PmgBoolean = PMGBOOLEAN__1
	this.Scriptedupdates = &scriptedupdates
	return &this
}

// NewConfigClamavUpdateClamavSectionRequestWithDefaults instantiates a new ConfigClamavUpdateClamavSectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigClamavUpdateClamavSectionRequestWithDefaults() *ConfigClamavUpdateClamavSectionRequest {
	this := ConfigClamavUpdateClamavSectionRequest{}

	var archiveblockencrypted PmgBoolean = PMGBOOLEAN__0
	this.Archiveblockencrypted = &archiveblockencrypted

	var archivemaxfiles int64 = 1000
	this.Archivemaxfiles = &archivemaxfiles

	var archivemaxrec int64 = 5
	this.Archivemaxrec = &archivemaxrec

	var archivemaxsize int64 = 25000000
	this.Archivemaxsize = &archivemaxsize

	var dbmirror string = "database.clamav.net"
	this.Dbmirror = &dbmirror



	var maxcccount int64 = 0
	this.Maxcccount = &maxcccount

	var maxscansize int64 = 100000000
	this.Maxscansize = &maxscansize

	var scriptedupdates PmgBoolean = PMGBOOLEAN__1
	this.Scriptedupdates = &scriptedupdates

	return &this
}


// GetArchiveblockencrypted returns the Archiveblockencrypted field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchiveblockencrypted() PmgBoolean {
	if o == nil || IsNil(o.Archiveblockencrypted) {
		var ret PmgBoolean
		return ret
	}
	return *o.Archiveblockencrypted
}

// GetArchiveblockencryptedOk returns a tuple with the Archiveblockencrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchiveblockencryptedOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Archiveblockencrypted) {
		return nil, false
	}
	return o.Archiveblockencrypted, true
}

// HasArchiveblockencrypted returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasArchiveblockencrypted() bool {
	if o != nil && !IsNil(o.Archiveblockencrypted) {
		return true
	}

	return false
}

// SetArchiveblockencrypted gets a reference to the given PmgBoolean and assigns it to the Archiveblockencrypted field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetArchiveblockencrypted(v PmgBoolean) {
	o.Archiveblockencrypted = &v
}


// GetArchivemaxfiles returns the Archivemaxfiles field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxfiles() int64 {
	if o == nil || IsNil(o.Archivemaxfiles) {
		var ret int64
		return ret
	}
	return *o.Archivemaxfiles
}

// GetArchivemaxfilesOk returns a tuple with the Archivemaxfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxfilesOk() (*int64, bool) {
	if o == nil || IsNil(o.Archivemaxfiles) {
		return nil, false
	}
	return o.Archivemaxfiles, true
}

// HasArchivemaxfiles returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasArchivemaxfiles() bool {
	if o != nil && !IsNil(o.Archivemaxfiles) {
		return true
	}

	return false
}

// SetArchivemaxfiles gets a reference to the given int64 and assigns it to the Archivemaxfiles field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetArchivemaxfiles(v int64) {
	o.Archivemaxfiles = &v
}


// GetArchivemaxrec returns the Archivemaxrec field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxrec() int64 {
	if o == nil || IsNil(o.Archivemaxrec) {
		var ret int64
		return ret
	}
	return *o.Archivemaxrec
}

// GetArchivemaxrecOk returns a tuple with the Archivemaxrec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxrecOk() (*int64, bool) {
	if o == nil || IsNil(o.Archivemaxrec) {
		return nil, false
	}
	return o.Archivemaxrec, true
}

// HasArchivemaxrec returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasArchivemaxrec() bool {
	if o != nil && !IsNil(o.Archivemaxrec) {
		return true
	}

	return false
}

// SetArchivemaxrec gets a reference to the given int64 and assigns it to the Archivemaxrec field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetArchivemaxrec(v int64) {
	o.Archivemaxrec = &v
}


// GetArchivemaxsize returns the Archivemaxsize field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxsize() int64 {
	if o == nil || IsNil(o.Archivemaxsize) {
		var ret int64
		return ret
	}
	return *o.Archivemaxsize
}

// GetArchivemaxsizeOk returns a tuple with the Archivemaxsize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetArchivemaxsizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Archivemaxsize) {
		return nil, false
	}
	return o.Archivemaxsize, true
}

// HasArchivemaxsize returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasArchivemaxsize() bool {
	if o != nil && !IsNil(o.Archivemaxsize) {
		return true
	}

	return false
}

// SetArchivemaxsize gets a reference to the given int64 and assigns it to the Archivemaxsize field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetArchivemaxsize(v int64) {
	o.Archivemaxsize = &v
}


// GetDbmirror returns the Dbmirror field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDbmirror() string {
	if o == nil || IsNil(o.Dbmirror) {
		var ret string
		return ret
	}
	return *o.Dbmirror
}

// GetDbmirrorOk returns a tuple with the Dbmirror field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDbmirrorOk() (*string, bool) {
	if o == nil || IsNil(o.Dbmirror) {
		return nil, false
	}
	return o.Dbmirror, true
}

// HasDbmirror returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasDbmirror() bool {
	if o != nil && !IsNil(o.Dbmirror) {
		return true
	}

	return false
}

// SetDbmirror gets a reference to the given string and assigns it to the Dbmirror field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetDbmirror(v string) {
	o.Dbmirror = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDelete() string {
	if o == nil || IsNil(o.Delete) {
		var ret string
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDeleteOk() (*string, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given string and assigns it to the Delete field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetDelete(v string) {
	o.Delete = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetMaxcccount returns the Maxcccount field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetMaxcccount() int64 {
	if o == nil || IsNil(o.Maxcccount) {
		var ret int64
		return ret
	}
	return *o.Maxcccount
}

// GetMaxcccountOk returns a tuple with the Maxcccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetMaxcccountOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxcccount) {
		return nil, false
	}
	return o.Maxcccount, true
}

// HasMaxcccount returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasMaxcccount() bool {
	if o != nil && !IsNil(o.Maxcccount) {
		return true
	}

	return false
}

// SetMaxcccount gets a reference to the given int64 and assigns it to the Maxcccount field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetMaxcccount(v int64) {
	o.Maxcccount = &v
}


// GetMaxscansize returns the Maxscansize field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetMaxscansize() int64 {
	if o == nil || IsNil(o.Maxscansize) {
		var ret int64
		return ret
	}
	return *o.Maxscansize
}

// GetMaxscansizeOk returns a tuple with the Maxscansize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetMaxscansizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxscansize) {
		return nil, false
	}
	return o.Maxscansize, true
}

// HasMaxscansize returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasMaxscansize() bool {
	if o != nil && !IsNil(o.Maxscansize) {
		return true
	}

	return false
}

// SetMaxscansize gets a reference to the given int64 and assigns it to the Maxscansize field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetMaxscansize(v int64) {
	o.Maxscansize = &v
}


// GetScriptedupdates returns the Scriptedupdates field value if set, zero value otherwise.
func (o *ConfigClamavUpdateClamavSectionRequest) GetScriptedupdates() PmgBoolean {
	if o == nil || IsNil(o.Scriptedupdates) {
		var ret PmgBoolean
		return ret
	}
	return *o.Scriptedupdates
}

// GetScriptedupdatesOk returns a tuple with the Scriptedupdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) GetScriptedupdatesOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Scriptedupdates) {
		return nil, false
	}
	return o.Scriptedupdates, true
}

// HasScriptedupdates returns a boolean if a field has been set.
func (o *ConfigClamavUpdateClamavSectionRequest) HasScriptedupdates() bool {
	if o != nil && !IsNil(o.Scriptedupdates) {
		return true
	}

	return false
}

// SetScriptedupdates gets a reference to the given PmgBoolean and assigns it to the Scriptedupdates field.
func (o *ConfigClamavUpdateClamavSectionRequest) SetScriptedupdates(v PmgBoolean) {
	o.Scriptedupdates = &v
}


func (o ConfigClamavUpdateClamavSectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigClamavUpdateClamavSectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Archiveblockencrypted) {
		toSerialize["archiveblockencrypted"] = o.Archiveblockencrypted
	}
	
	if !IsNil(o.Archivemaxfiles) {
		toSerialize["archivemaxfiles"] = o.Archivemaxfiles
	}
	
	if !IsNil(o.Archivemaxrec) {
		toSerialize["archivemaxrec"] = o.Archivemaxrec
	}
	
	if !IsNil(o.Archivemaxsize) {
		toSerialize["archivemaxsize"] = o.Archivemaxsize
	}
	
	if !IsNil(o.Dbmirror) {
		toSerialize["dbmirror"] = o.Dbmirror
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Maxcccount) {
		toSerialize["maxcccount"] = o.Maxcccount
	}
	
	if !IsNil(o.Maxscansize) {
		toSerialize["maxscansize"] = o.Maxscansize
	}
	
	if !IsNil(o.Scriptedupdates) {
		toSerialize["scriptedupdates"] = o.Scriptedupdates
	}
	
	return toSerialize, nil
}

type NullableConfigClamavUpdateClamavSectionRequest struct {
	value *ConfigClamavUpdateClamavSectionRequest
	isSet bool
}

func (v NullableConfigClamavUpdateClamavSectionRequest) Get() *ConfigClamavUpdateClamavSectionRequest {
	return v.value
}

func (v *NullableConfigClamavUpdateClamavSectionRequest) Set(val *ConfigClamavUpdateClamavSectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigClamavUpdateClamavSectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigClamavUpdateClamavSectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigClamavUpdateClamavSectionRequest(val *ConfigClamavUpdateClamavSectionRequest) *NullableConfigClamavUpdateClamavSectionRequest {
	return &NullableConfigClamavUpdateClamavSectionRequest{value: val, isSet: true}
}

func (v NullableConfigClamavUpdateClamavSectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigClamavUpdateClamavSectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


