/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodesPostfixQueueActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesPostfixQueueActionRequest{}

// NodesPostfixQueueActionRequest struct for NodesPostfixQueueActionRequest
type NodesPostfixQueueActionRequest struct {

	// Operation to perform on the given IDs.
	Action PmgNodesPostfixActionEnum `json:"action"`

	// Queue ID(s).
	Ids string `json:"ids"`

}

type _NodesPostfixQueueActionRequest NodesPostfixQueueActionRequest

// NewNodesPostfixQueueActionRequest instantiates a new NodesPostfixQueueActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesPostfixQueueActionRequest(action PmgNodesPostfixActionEnum, ids string) *NodesPostfixQueueActionRequest {
	this := NodesPostfixQueueActionRequest{}
	this.Action = action
	this.Ids = ids
	return &this
}

// NewNodesPostfixQueueActionRequestWithDefaults instantiates a new NodesPostfixQueueActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesPostfixQueueActionRequestWithDefaults() *NodesPostfixQueueActionRequest {
	this := NodesPostfixQueueActionRequest{}



	return &this
}


// GetAction returns the Action field value
func (o *NodesPostfixQueueActionRequest) GetAction() PmgNodesPostfixActionEnum {
	if o == nil {
		var ret PmgNodesPostfixActionEnum
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *NodesPostfixQueueActionRequest) GetActionOk() (*PmgNodesPostfixActionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *NodesPostfixQueueActionRequest) SetAction(v PmgNodesPostfixActionEnum) {
	o.Action = v
}


// GetIds returns the Ids field value
func (o *NodesPostfixQueueActionRequest) GetIds() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *NodesPostfixQueueActionRequest) GetIdsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ids, true
}

// SetIds sets field value
func (o *NodesPostfixQueueActionRequest) SetIds(v string) {
	o.Ids = v
}


func (o NodesPostfixQueueActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesPostfixQueueActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["action"] = o.Action
	
	toSerialize["ids"] = o.Ids
	
	return toSerialize, nil
}

func (o *NodesPostfixQueueActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesPostfixQueueActionRequest := _NodesPostfixQueueActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodesPostfixQueueActionRequest)

	if err != nil {
		return err
	}

	*o = NodesPostfixQueueActionRequest(varNodesPostfixQueueActionRequest)

	return err
}

type NullableNodesPostfixQueueActionRequest struct {
	value *NodesPostfixQueueActionRequest
	isSet bool
}

func (v NullableNodesPostfixQueueActionRequest) Get() *NodesPostfixQueueActionRequest {
	return v.value
}

func (v *NullableNodesPostfixQueueActionRequest) Set(val *NodesPostfixQueueActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesPostfixQueueActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesPostfixQueueActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesPostfixQueueActionRequest(val *NodesPostfixQueueActionRequest) *NullableNodesPostfixQueueActionRequest {
	return &NullableNodesPostfixQueueActionRequest{value: val, isSet: true}
}

func (v NullableNodesPostfixQueueActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesPostfixQueueActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


