/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigAcmeUpdateAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAcmeUpdateAccountRequest{}

// ConfigAcmeUpdateAccountRequest struct for ConfigAcmeUpdateAccountRequest
type ConfigAcmeUpdateAccountRequest struct {

	// Contact email addresses.
	Contact *string `json:"contact,omitempty"`

}

// NewConfigAcmeUpdateAccountRequest instantiates a new ConfigAcmeUpdateAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAcmeUpdateAccountRequest() *ConfigAcmeUpdateAccountRequest {
	this := ConfigAcmeUpdateAccountRequest{}
	return &this
}

// NewConfigAcmeUpdateAccountRequestWithDefaults instantiates a new ConfigAcmeUpdateAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAcmeUpdateAccountRequestWithDefaults() *ConfigAcmeUpdateAccountRequest {
	this := ConfigAcmeUpdateAccountRequest{}


	return &this
}


// GetContact returns the Contact field value if set, zero value otherwise.
func (o *ConfigAcmeUpdateAccountRequest) GetContact() string {
	if o == nil || IsNil(o.Contact) {
		var ret string
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAcmeUpdateAccountRequest) GetContactOk() (*string, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *ConfigAcmeUpdateAccountRequest) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given string and assigns it to the Contact field.
func (o *ConfigAcmeUpdateAccountRequest) SetContact(v string) {
	o.Contact = &v
}


func (o ConfigAcmeUpdateAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAcmeUpdateAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	
	return toSerialize, nil
}

type NullableConfigAcmeUpdateAccountRequest struct {
	value *ConfigAcmeUpdateAccountRequest
	isSet bool
}

func (v NullableConfigAcmeUpdateAccountRequest) Get() *ConfigAcmeUpdateAccountRequest {
	return v.value
}

func (v *NullableConfigAcmeUpdateAccountRequest) Set(val *ConfigAcmeUpdateAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAcmeUpdateAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAcmeUpdateAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAcmeUpdateAccountRequest(val *ConfigAcmeUpdateAccountRequest) *NullableConfigAcmeUpdateAccountRequest {
	return &NullableConfigAcmeUpdateAccountRequest{value: val, isSet: true}
}

func (v NullableConfigAcmeUpdateAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAcmeUpdateAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


