/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgFileTypeEnum the model 'PmgFileTypeEnum'
type PmgFileTypeEnum string

// List of PmgFileTypeEnum
const (
	PMGFILETYPEENUM_LIST PmgFileTypeEnum = "list"
	PMGFILETYPEENUM_SOURCES PmgFileTypeEnum = "sources"
)

// All allowed values of PmgFileTypeEnum enum
var AllowedPmgFileTypeEnumEnumValues = []PmgFileTypeEnum{
	"list",
	"sources",
}

func (v *PmgFileTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgFileTypeEnum(value)
	for _, existing := range AllowedPmgFileTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgFileTypeEnum", value)
}

// NewPmgFileTypeEnumFromValue returns a pointer to a valid PmgFileTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgFileTypeEnumFromValue(v string) (*PmgFileTypeEnum, error) {
	ev := PmgFileTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgFileTypeEnum: valid values are %v", v, AllowedPmgFileTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgFileTypeEnum) IsValid() bool {
	for _, existing := range AllowedPmgFileTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgFileTypeEnum value
func (v PmgFileTypeEnum) Ptr() *PmgFileTypeEnum {
	return &v
}

type NullablePmgFileTypeEnum struct {
	value *PmgFileTypeEnum
	isSet bool
}

func (v NullablePmgFileTypeEnum) Get() *PmgFileTypeEnum {
	return v.value
}

func (v *NullablePmgFileTypeEnum) Set(val *PmgFileTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgFileTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgFileTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgFileTypeEnum(val *PmgFileTypeEnum) *NullablePmgFileTypeEnum {
	return &NullablePmgFileTypeEnum{value: val, isSet: true}
}

func (v NullablePmgFileTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgFileTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

