/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigCustomscoresListScoresResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigCustomscoresListScoresResponseDataInner{}

// ConfigCustomscoresListScoresResponseDataInner struct for ConfigCustomscoresListScoresResponseDataInner
type ConfigCustomscoresListScoresResponseDataInner struct {

	// The Comment.
	Comment *string `json:"comment,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// The name of the rule.
	Name string `json:"name" validate:"regexp=[a-zA-Z\\\\_\\\\-\\\\.0-9]+"`

	// The score the rule should be valued at.
	Score *float32 `json:"score,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ConfigCustomscoresListScoresResponseDataInner ConfigCustomscoresListScoresResponseDataInner

// NewConfigCustomscoresListScoresResponseDataInner instantiates a new ConfigCustomscoresListScoresResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigCustomscoresListScoresResponseDataInner(name string) *ConfigCustomscoresListScoresResponseDataInner {
	this := ConfigCustomscoresListScoresResponseDataInner{}
	this.Name = name
	return &this
}

// NewConfigCustomscoresListScoresResponseDataInnerWithDefaults instantiates a new ConfigCustomscoresListScoresResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigCustomscoresListScoresResponseDataInnerWithDefaults() *ConfigCustomscoresListScoresResponseDataInner {
	this := ConfigCustomscoresListScoresResponseDataInner{}





	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigCustomscoresListScoresResponseDataInner) SetComment(v string) {
	o.Comment = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigCustomscoresListScoresResponseDataInner) SetDigest(v string) {
	o.Digest = &v
}


// GetName returns the Name field value
func (o *ConfigCustomscoresListScoresResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigCustomscoresListScoresResponseDataInner) SetName(v string) {
	o.Name = v
}


// GetScore returns the Score field value if set, zero value otherwise.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *ConfigCustomscoresListScoresResponseDataInner) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *ConfigCustomscoresListScoresResponseDataInner) SetScore(v float32) {
	o.Score = &v
}


func (o ConfigCustomscoresListScoresResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigCustomscoresListScoresResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigCustomscoresListScoresResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigCustomscoresListScoresResponseDataInner := _ConfigCustomscoresListScoresResponseDataInner{}

	err = json.Unmarshal(data, &varConfigCustomscoresListScoresResponseDataInner)

	if err != nil {
		return err
	}

	*o = ConfigCustomscoresListScoresResponseDataInner(varConfigCustomscoresListScoresResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "comment")
		delete(additionalProperties, "digest")
		delete(additionalProperties, "name")
		delete(additionalProperties, "score")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigCustomscoresListScoresResponseDataInner struct {
	value *ConfigCustomscoresListScoresResponseDataInner
	isSet bool
}

func (v NullableConfigCustomscoresListScoresResponseDataInner) Get() *ConfigCustomscoresListScoresResponseDataInner {
	return v.value
}

func (v *NullableConfigCustomscoresListScoresResponseDataInner) Set(val *ConfigCustomscoresListScoresResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigCustomscoresListScoresResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigCustomscoresListScoresResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigCustomscoresListScoresResponseDataInner(val *ConfigCustomscoresListScoresResponseDataInner) *NullableConfigCustomscoresListScoresResponseDataInner {
	return &NullableConfigCustomscoresListScoresResponseDataInner{value: val, isSet: true}
}

func (v NullableConfigCustomscoresListScoresResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigCustomscoresListScoresResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


