/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgNodesCmdEnum the model 'PmgNodesCmdEnum'
type PmgNodesCmdEnum string

// List of PmgNodesCmdEnum
const (
	PMGNODESCMDENUM_LOGIN PmgNodesCmdEnum = "login"
	PMGNODESCMDENUM_UPGRADE PmgNodesCmdEnum = "upgrade"
)

// All allowed values of PmgNodesCmdEnum enum
var AllowedPmgNodesCmdEnumEnumValues = []PmgNodesCmdEnum{
	"login",
	"upgrade",
}

func (v *PmgNodesCmdEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgNodesCmdEnum(value)
	for _, existing := range AllowedPmgNodesCmdEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgNodesCmdEnum", value)
}

// NewPmgNodesCmdEnumFromValue returns a pointer to a valid PmgNodesCmdEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgNodesCmdEnumFromValue(v string) (*PmgNodesCmdEnum, error) {
	ev := PmgNodesCmdEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgNodesCmdEnum: valid values are %v", v, AllowedPmgNodesCmdEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgNodesCmdEnum) IsValid() bool {
	for _, existing := range AllowedPmgNodesCmdEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgNodesCmdEnum value
func (v PmgNodesCmdEnum) Ptr() *PmgNodesCmdEnum {
	return &v
}

type NullablePmgNodesCmdEnum struct {
	value *PmgNodesCmdEnum
	isSet bool
}

func (v NullablePmgNodesCmdEnum) Get() *PmgNodesCmdEnum {
	return v.value
}

func (v *NullablePmgNodesCmdEnum) Set(val *PmgNodesCmdEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgNodesCmdEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgNodesCmdEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgNodesCmdEnum(val *PmgNodesCmdEnum) *NullablePmgNodesCmdEnum {
	return &NullablePmgNodesCmdEnum{value: val, isSet: true}
}

func (v NullablePmgNodesCmdEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgNodesCmdEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

