/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StatisticsMaildistributionResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsMaildistributionResponseDataInner{}

// StatisticsMaildistributionResponseDataInner struct for StatisticsMaildistributionResponseDataInner
type StatisticsMaildistributionResponseDataInner struct {

	// Incoming bounce mail count (sender = <>).
	BouncesIn float32 `json:"bounces_in"`

	// Outgoing bounce mail count (sender = <>).
	BouncesOut float32 `json:"bounces_out"`

	// Overall mail count (in and out).
	Count float32 `json:"count"`

	// Incoming mail count.
	CountIn float32 `json:"count_in"`

	// Outgoing mail count.
	CountOut float32 `json:"count_out"`

	// Hour (0-23).
	Index int64 `json:"index"`

	// Incoming spam mails (spamcount_in + glcount + spfcount).
	SpamcountIn float32 `json:"spamcount_in"`

	// Outgoing spam mails.
	SpamcountOut float32 `json:"spamcount_out"`

	// Number of incoming virus mails.
	ViruscountIn float32 `json:"viruscount_in"`

	// Number of outgoing virus mails.
	ViruscountOut float32 `json:"viruscount_out"`

	AdditionalProperties map[string]interface{}
}

type _StatisticsMaildistributionResponseDataInner StatisticsMaildistributionResponseDataInner

// NewStatisticsMaildistributionResponseDataInner instantiates a new StatisticsMaildistributionResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsMaildistributionResponseDataInner(bouncesIn float32, bouncesOut float32, count float32, countIn float32, countOut float32, index int64, spamcountIn float32, spamcountOut float32, viruscountIn float32, viruscountOut float32) *StatisticsMaildistributionResponseDataInner {
	this := StatisticsMaildistributionResponseDataInner{}
	this.BouncesIn = bouncesIn
	this.BouncesOut = bouncesOut
	this.Count = count
	this.CountIn = countIn
	this.CountOut = countOut
	this.Index = index
	this.SpamcountIn = spamcountIn
	this.SpamcountOut = spamcountOut
	this.ViruscountIn = viruscountIn
	this.ViruscountOut = viruscountOut
	return &this
}

// NewStatisticsMaildistributionResponseDataInnerWithDefaults instantiates a new StatisticsMaildistributionResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsMaildistributionResponseDataInnerWithDefaults() *StatisticsMaildistributionResponseDataInner {
	this := StatisticsMaildistributionResponseDataInner{}











	return &this
}


// GetBouncesIn returns the BouncesIn field value
func (o *StatisticsMaildistributionResponseDataInner) GetBouncesIn() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BouncesIn
}

// GetBouncesInOk returns a tuple with the BouncesIn field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetBouncesInOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BouncesIn, true
}

// SetBouncesIn sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetBouncesIn(v float32) {
	o.BouncesIn = v
}


// GetBouncesOut returns the BouncesOut field value
func (o *StatisticsMaildistributionResponseDataInner) GetBouncesOut() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BouncesOut
}

// GetBouncesOutOk returns a tuple with the BouncesOut field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetBouncesOutOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BouncesOut, true
}

// SetBouncesOut sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetBouncesOut(v float32) {
	o.BouncesOut = v
}


// GetCount returns the Count field value
func (o *StatisticsMaildistributionResponseDataInner) GetCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetCount(v float32) {
	o.Count = v
}


// GetCountIn returns the CountIn field value
func (o *StatisticsMaildistributionResponseDataInner) GetCountIn() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CountIn
}

// GetCountInOk returns a tuple with the CountIn field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetCountInOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountIn, true
}

// SetCountIn sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetCountIn(v float32) {
	o.CountIn = v
}


// GetCountOut returns the CountOut field value
func (o *StatisticsMaildistributionResponseDataInner) GetCountOut() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CountOut
}

// GetCountOutOk returns a tuple with the CountOut field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetCountOutOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountOut, true
}

// SetCountOut sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetCountOut(v float32) {
	o.CountOut = v
}


// GetIndex returns the Index field value
func (o *StatisticsMaildistributionResponseDataInner) GetIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetIndex(v int64) {
	o.Index = v
}


// GetSpamcountIn returns the SpamcountIn field value
func (o *StatisticsMaildistributionResponseDataInner) GetSpamcountIn() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SpamcountIn
}

// GetSpamcountInOk returns a tuple with the SpamcountIn field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetSpamcountInOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpamcountIn, true
}

// SetSpamcountIn sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetSpamcountIn(v float32) {
	o.SpamcountIn = v
}


// GetSpamcountOut returns the SpamcountOut field value
func (o *StatisticsMaildistributionResponseDataInner) GetSpamcountOut() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SpamcountOut
}

// GetSpamcountOutOk returns a tuple with the SpamcountOut field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetSpamcountOutOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpamcountOut, true
}

// SetSpamcountOut sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetSpamcountOut(v float32) {
	o.SpamcountOut = v
}


// GetViruscountIn returns the ViruscountIn field value
func (o *StatisticsMaildistributionResponseDataInner) GetViruscountIn() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ViruscountIn
}

// GetViruscountInOk returns a tuple with the ViruscountIn field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetViruscountInOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViruscountIn, true
}

// SetViruscountIn sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetViruscountIn(v float32) {
	o.ViruscountIn = v
}


// GetViruscountOut returns the ViruscountOut field value
func (o *StatisticsMaildistributionResponseDataInner) GetViruscountOut() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ViruscountOut
}

// GetViruscountOutOk returns a tuple with the ViruscountOut field value
// and a boolean to check if the value has been set.
func (o *StatisticsMaildistributionResponseDataInner) GetViruscountOutOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViruscountOut, true
}

// SetViruscountOut sets field value
func (o *StatisticsMaildistributionResponseDataInner) SetViruscountOut(v float32) {
	o.ViruscountOut = v
}


func (o StatisticsMaildistributionResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsMaildistributionResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["bounces_in"] = o.BouncesIn
	
	toSerialize["bounces_out"] = o.BouncesOut
	
	toSerialize["count"] = o.Count
	
	toSerialize["count_in"] = o.CountIn
	
	toSerialize["count_out"] = o.CountOut
	
	toSerialize["index"] = o.Index
	
	toSerialize["spamcount_in"] = o.SpamcountIn
	
	toSerialize["spamcount_out"] = o.SpamcountOut
	
	toSerialize["viruscount_in"] = o.ViruscountIn
	
	toSerialize["viruscount_out"] = o.ViruscountOut
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatisticsMaildistributionResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bounces_in",
		"bounces_out",
		"count",
		"count_in",
		"count_out",
		"index",
		"spamcount_in",
		"spamcount_out",
		"viruscount_in",
		"viruscount_out",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatisticsMaildistributionResponseDataInner := _StatisticsMaildistributionResponseDataInner{}

	err = json.Unmarshal(data, &varStatisticsMaildistributionResponseDataInner)

	if err != nil {
		return err
	}

	*o = StatisticsMaildistributionResponseDataInner(varStatisticsMaildistributionResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bounces_in")
		delete(additionalProperties, "bounces_out")
		delete(additionalProperties, "count")
		delete(additionalProperties, "count_in")
		delete(additionalProperties, "count_out")
		delete(additionalProperties, "index")
		delete(additionalProperties, "spamcount_in")
		delete(additionalProperties, "spamcount_out")
		delete(additionalProperties, "viruscount_in")
		delete(additionalProperties, "viruscount_out")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatisticsMaildistributionResponseDataInner struct {
	value *StatisticsMaildistributionResponseDataInner
	isSet bool
}

func (v NullableStatisticsMaildistributionResponseDataInner) Get() *StatisticsMaildistributionResponseDataInner {
	return v.value
}

func (v *NullableStatisticsMaildistributionResponseDataInner) Set(val *StatisticsMaildistributionResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsMaildistributionResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsMaildistributionResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsMaildistributionResponseDataInner(val *StatisticsMaildistributionResponseDataInner) *NullableStatisticsMaildistributionResponseDataInner {
	return &NullableStatisticsMaildistributionResponseDataInner{value: val, isSet: true}
}

func (v NullableStatisticsMaildistributionResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsMaildistributionResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


