/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgBondXmitHashPolicyEnum the model 'PmgBondXmitHashPolicyEnum'
type PmgBondXmitHashPolicyEnum string

// List of PmgBondXmitHashPolicyEnum
const (
	PMGBONDXMITHASHPOLICYENUM_LAYER2 PmgBondXmitHashPolicyEnum = "layer2"
	PMGBONDXMITHASHPOLICYENUM_LAYER23 PmgBondXmitHashPolicyEnum = "layer2+3"
	PMGBONDXMITHASHPOLICYENUM_LAYER34 PmgBondXmitHashPolicyEnum = "layer3+4"
)

// All allowed values of PmgBondXmitHashPolicyEnum enum
var AllowedPmgBondXmitHashPolicyEnumEnumValues = []PmgBondXmitHashPolicyEnum{
	"layer2",
	"layer2+3",
	"layer3+4",
}

func (v *PmgBondXmitHashPolicyEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgBondXmitHashPolicyEnum(value)
	for _, existing := range AllowedPmgBondXmitHashPolicyEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgBondXmitHashPolicyEnum", value)
}

// NewPmgBondXmitHashPolicyEnumFromValue returns a pointer to a valid PmgBondXmitHashPolicyEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgBondXmitHashPolicyEnumFromValue(v string) (*PmgBondXmitHashPolicyEnum, error) {
	ev := PmgBondXmitHashPolicyEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgBondXmitHashPolicyEnum: valid values are %v", v, AllowedPmgBondXmitHashPolicyEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgBondXmitHashPolicyEnum) IsValid() bool {
	for _, existing := range AllowedPmgBondXmitHashPolicyEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgBondXmitHashPolicyEnum value
func (v PmgBondXmitHashPolicyEnum) Ptr() *PmgBondXmitHashPolicyEnum {
	return &v
}

type NullablePmgBondXmitHashPolicyEnum struct {
	value *PmgBondXmitHashPolicyEnum
	isSet bool
}

func (v NullablePmgBondXmitHashPolicyEnum) Get() *PmgBondXmitHashPolicyEnum {
	return v.value
}

func (v *NullablePmgBondXmitHashPolicyEnum) Set(val *PmgBondXmitHashPolicyEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgBondXmitHashPolicyEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgBondXmitHashPolicyEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgBondXmitHashPolicyEnum(val *PmgBondXmitHashPolicyEnum) *NullablePmgBondXmitHashPolicyEnum {
	return &NullablePmgBondXmitHashPolicyEnum{value: val, isSet: true}
}

func (v NullablePmgBondXmitHashPolicyEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgBondXmitHashPolicyEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

