/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgNodesPostfixSortfieldEnum the model 'PmgNodesPostfixSortfieldEnum'
type PmgNodesPostfixSortfieldEnum string

// List of PmgNodesPostfixSortfieldEnum
const (
	PMGNODESPOSTFIXSORTFIELDENUM_ARRIVAL_TIME PmgNodesPostfixSortfieldEnum = "arrival_time"
	PMGNODESPOSTFIXSORTFIELDENUM_MESSAGE_SIZE PmgNodesPostfixSortfieldEnum = "message_size"
	PMGNODESPOSTFIXSORTFIELDENUM_SENDER PmgNodesPostfixSortfieldEnum = "sender"
	PMGNODESPOSTFIXSORTFIELDENUM_RECEIVER PmgNodesPostfixSortfieldEnum = "receiver"
	PMGNODESPOSTFIXSORTFIELDENUM_REASON PmgNodesPostfixSortfieldEnum = "reason"
)

// All allowed values of PmgNodesPostfixSortfieldEnum enum
var AllowedPmgNodesPostfixSortfieldEnumEnumValues = []PmgNodesPostfixSortfieldEnum{
	"arrival_time",
	"message_size",
	"sender",
	"receiver",
	"reason",
}

func (v *PmgNodesPostfixSortfieldEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgNodesPostfixSortfieldEnum(value)
	for _, existing := range AllowedPmgNodesPostfixSortfieldEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgNodesPostfixSortfieldEnum", value)
}

// NewPmgNodesPostfixSortfieldEnumFromValue returns a pointer to a valid PmgNodesPostfixSortfieldEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgNodesPostfixSortfieldEnumFromValue(v string) (*PmgNodesPostfixSortfieldEnum, error) {
	ev := PmgNodesPostfixSortfieldEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgNodesPostfixSortfieldEnum: valid values are %v", v, AllowedPmgNodesPostfixSortfieldEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgNodesPostfixSortfieldEnum) IsValid() bool {
	for _, existing := range AllowedPmgNodesPostfixSortfieldEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgNodesPostfixSortfieldEnum value
func (v PmgNodesPostfixSortfieldEnum) Ptr() *PmgNodesPostfixSortfieldEnum {
	return &v
}

type NullablePmgNodesPostfixSortfieldEnum struct {
	value *PmgNodesPostfixSortfieldEnum
	isSet bool
}

func (v NullablePmgNodesPostfixSortfieldEnum) Get() *PmgNodesPostfixSortfieldEnum {
	return v.value
}

func (v *NullablePmgNodesPostfixSortfieldEnum) Set(val *PmgNodesPostfixSortfieldEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgNodesPostfixSortfieldEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgNodesPostfixSortfieldEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgNodesPostfixSortfieldEnum(val *PmgNodesPostfixSortfieldEnum) *NullablePmgNodesPostfixSortfieldEnum {
	return &NullablePmgNodesPostfixSortfieldEnum{value: val, isSet: true}
}

func (v NullablePmgNodesPostfixSortfieldEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgNodesPostfixSortfieldEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

