/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigCustomscoresApplyScoreChangesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigCustomscoresApplyScoreChangesRequest{}

// ConfigCustomscoresApplyScoreChangesRequest struct for ConfigCustomscoresApplyScoreChangesRequest
type ConfigCustomscoresApplyScoreChangesRequest struct {

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// If set, also restarts pmg-smtp-filter. This is necessary for the changes to work.
	RestartDaemon *PmgBoolean `json:"restart-daemon,omitempty"`

}

// NewConfigCustomscoresApplyScoreChangesRequest instantiates a new ConfigCustomscoresApplyScoreChangesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigCustomscoresApplyScoreChangesRequest() *ConfigCustomscoresApplyScoreChangesRequest {
	this := ConfigCustomscoresApplyScoreChangesRequest{}
	var restartDaemon PmgBoolean = PMGBOOLEAN__0
	this.RestartDaemon = &restartDaemon
	return &this
}

// NewConfigCustomscoresApplyScoreChangesRequestWithDefaults instantiates a new ConfigCustomscoresApplyScoreChangesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigCustomscoresApplyScoreChangesRequestWithDefaults() *ConfigCustomscoresApplyScoreChangesRequest {
	this := ConfigCustomscoresApplyScoreChangesRequest{}


	var restartDaemon PmgBoolean = PMGBOOLEAN__0
	this.RestartDaemon = &restartDaemon

	return &this
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigCustomscoresApplyScoreChangesRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresApplyScoreChangesRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigCustomscoresApplyScoreChangesRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigCustomscoresApplyScoreChangesRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetRestartDaemon returns the RestartDaemon field value if set, zero value otherwise.
func (o *ConfigCustomscoresApplyScoreChangesRequest) GetRestartDaemon() PmgBoolean {
	if o == nil || IsNil(o.RestartDaemon) {
		var ret PmgBoolean
		return ret
	}
	return *o.RestartDaemon
}

// GetRestartDaemonOk returns a tuple with the RestartDaemon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigCustomscoresApplyScoreChangesRequest) GetRestartDaemonOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.RestartDaemon) {
		return nil, false
	}
	return o.RestartDaemon, true
}

// HasRestartDaemon returns a boolean if a field has been set.
func (o *ConfigCustomscoresApplyScoreChangesRequest) HasRestartDaemon() bool {
	if o != nil && !IsNil(o.RestartDaemon) {
		return true
	}

	return false
}

// SetRestartDaemon gets a reference to the given PmgBoolean and assigns it to the RestartDaemon field.
func (o *ConfigCustomscoresApplyScoreChangesRequest) SetRestartDaemon(v PmgBoolean) {
	o.RestartDaemon = &v
}


func (o ConfigCustomscoresApplyScoreChangesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigCustomscoresApplyScoreChangesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.RestartDaemon) {
		toSerialize["restart-daemon"] = o.RestartDaemon
	}
	
	return toSerialize, nil
}

type NullableConfigCustomscoresApplyScoreChangesRequest struct {
	value *ConfigCustomscoresApplyScoreChangesRequest
	isSet bool
}

func (v NullableConfigCustomscoresApplyScoreChangesRequest) Get() *ConfigCustomscoresApplyScoreChangesRequest {
	return v.value
}

func (v *NullableConfigCustomscoresApplyScoreChangesRequest) Set(val *ConfigCustomscoresApplyScoreChangesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigCustomscoresApplyScoreChangesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigCustomscoresApplyScoreChangesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigCustomscoresApplyScoreChangesRequest(val *ConfigCustomscoresApplyScoreChangesRequest) *NullableConfigCustomscoresApplyScoreChangesRequest {
	return &NullableConfigCustomscoresApplyScoreChangesRequest{value: val, isSet: true}
}

func (v NullableConfigCustomscoresApplyScoreChangesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigCustomscoresApplyScoreChangesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


