/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigLdapProfileListGroupsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigLdapProfileListGroupsResponseDataInner{}

// ConfigLdapProfileListGroupsResponseDataInner struct for ConfigLdapProfileListGroupsResponseDataInner
type ConfigLdapProfileListGroupsResponseDataInner struct {

	Dn string `json:"dn"`

	Gid float32 `json:"gid"`

	AdditionalProperties map[string]interface{}
}

type _ConfigLdapProfileListGroupsResponseDataInner ConfigLdapProfileListGroupsResponseDataInner

// NewConfigLdapProfileListGroupsResponseDataInner instantiates a new ConfigLdapProfileListGroupsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigLdapProfileListGroupsResponseDataInner(dn string, gid float32) *ConfigLdapProfileListGroupsResponseDataInner {
	this := ConfigLdapProfileListGroupsResponseDataInner{}
	this.Dn = dn
	this.Gid = gid
	return &this
}

// NewConfigLdapProfileListGroupsResponseDataInnerWithDefaults instantiates a new ConfigLdapProfileListGroupsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigLdapProfileListGroupsResponseDataInnerWithDefaults() *ConfigLdapProfileListGroupsResponseDataInner {
	this := ConfigLdapProfileListGroupsResponseDataInner{}



	return &this
}


// GetDn returns the Dn field value
func (o *ConfigLdapProfileListGroupsResponseDataInner) GetDn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dn
}

// GetDnOk returns a tuple with the Dn field value
// and a boolean to check if the value has been set.
func (o *ConfigLdapProfileListGroupsResponseDataInner) GetDnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dn, true
}

// SetDn sets field value
func (o *ConfigLdapProfileListGroupsResponseDataInner) SetDn(v string) {
	o.Dn = v
}


// GetGid returns the Gid field value
func (o *ConfigLdapProfileListGroupsResponseDataInner) GetGid() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Gid
}

// GetGidOk returns a tuple with the Gid field value
// and a boolean to check if the value has been set.
func (o *ConfigLdapProfileListGroupsResponseDataInner) GetGidOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gid, true
}

// SetGid sets field value
func (o *ConfigLdapProfileListGroupsResponseDataInner) SetGid(v float32) {
	o.Gid = v
}


func (o ConfigLdapProfileListGroupsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigLdapProfileListGroupsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["dn"] = o.Dn
	
	toSerialize["gid"] = o.Gid
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigLdapProfileListGroupsResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dn",
		"gid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigLdapProfileListGroupsResponseDataInner := _ConfigLdapProfileListGroupsResponseDataInner{}

	err = json.Unmarshal(data, &varConfigLdapProfileListGroupsResponseDataInner)

	if err != nil {
		return err
	}

	*o = ConfigLdapProfileListGroupsResponseDataInner(varConfigLdapProfileListGroupsResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dn")
		delete(additionalProperties, "gid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigLdapProfileListGroupsResponseDataInner struct {
	value *ConfigLdapProfileListGroupsResponseDataInner
	isSet bool
}

func (v NullableConfigLdapProfileListGroupsResponseDataInner) Get() *ConfigLdapProfileListGroupsResponseDataInner {
	return v.value
}

func (v *NullableConfigLdapProfileListGroupsResponseDataInner) Set(val *ConfigLdapProfileListGroupsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigLdapProfileListGroupsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigLdapProfileListGroupsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigLdapProfileListGroupsResponseDataInner(val *ConfigLdapProfileListGroupsResponseDataInner) *NullableConfigLdapProfileListGroupsResponseDataInner {
	return &NullableConfigLdapProfileListGroupsResponseDataInner{value: val, isSet: true}
}

func (v NullableConfigLdapProfileListGroupsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigLdapProfileListGroupsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


