/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StatisticsDetailstatsResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsDetailstatsResponseDataInner{}

// StatisticsDetailstatsResponseDataInner struct for StatisticsDetailstatsResponseDataInner
type StatisticsDetailstatsResponseDataInner struct {

	// Mail was blocked.
	Blocked PmgBoolean `json:"blocked"`

	// Mail traffic (Bytes).
	Bytes float32 `json:"bytes"`

	// Receiver email. (for sender statistics)
	Receiver *string `json:"receiver,omitempty"`

	// Sender email. (for contact and receiver statistics)
	Sender *string `json:"sender,omitempty"`

	// Spam score.
	Spamlevel float32 `json:"spamlevel"`

	// Receive time stamp
	Time int64 `json:"time"`

	// Virus name.
	Virusinfo *string `json:"virusinfo,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _StatisticsDetailstatsResponseDataInner StatisticsDetailstatsResponseDataInner

// NewStatisticsDetailstatsResponseDataInner instantiates a new StatisticsDetailstatsResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsDetailstatsResponseDataInner(blocked PmgBoolean, bytes float32, spamlevel float32, time int64) *StatisticsDetailstatsResponseDataInner {
	this := StatisticsDetailstatsResponseDataInner{}
	this.Blocked = blocked
	this.Bytes = bytes
	this.Spamlevel = spamlevel
	this.Time = time
	return &this
}

// NewStatisticsDetailstatsResponseDataInnerWithDefaults instantiates a new StatisticsDetailstatsResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsDetailstatsResponseDataInnerWithDefaults() *StatisticsDetailstatsResponseDataInner {
	this := StatisticsDetailstatsResponseDataInner{}








	return &this
}


// GetBlocked returns the Blocked field value
func (o *StatisticsDetailstatsResponseDataInner) GetBlocked() PmgBoolean {
	if o == nil {
		var ret PmgBoolean
		return ret
	}

	return o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetBlockedOk() (*PmgBoolean, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Blocked, true
}

// SetBlocked sets field value
func (o *StatisticsDetailstatsResponseDataInner) SetBlocked(v PmgBoolean) {
	o.Blocked = v
}


// GetBytes returns the Bytes field value
func (o *StatisticsDetailstatsResponseDataInner) GetBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *StatisticsDetailstatsResponseDataInner) SetBytes(v float32) {
	o.Bytes = v
}


// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *StatisticsDetailstatsResponseDataInner) GetReceiver() string {
	if o == nil || IsNil(o.Receiver) {
		var ret string
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetReceiverOk() (*string, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *StatisticsDetailstatsResponseDataInner) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given string and assigns it to the Receiver field.
func (o *StatisticsDetailstatsResponseDataInner) SetReceiver(v string) {
	o.Receiver = &v
}


// GetSender returns the Sender field value if set, zero value otherwise.
func (o *StatisticsDetailstatsResponseDataInner) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *StatisticsDetailstatsResponseDataInner) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *StatisticsDetailstatsResponseDataInner) SetSender(v string) {
	o.Sender = &v
}


// GetSpamlevel returns the Spamlevel field value
func (o *StatisticsDetailstatsResponseDataInner) GetSpamlevel() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Spamlevel
}

// GetSpamlevelOk returns a tuple with the Spamlevel field value
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetSpamlevelOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spamlevel, true
}

// SetSpamlevel sets field value
func (o *StatisticsDetailstatsResponseDataInner) SetSpamlevel(v float32) {
	o.Spamlevel = v
}


// GetTime returns the Time field value
func (o *StatisticsDetailstatsResponseDataInner) GetTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *StatisticsDetailstatsResponseDataInner) SetTime(v int64) {
	o.Time = v
}


// GetVirusinfo returns the Virusinfo field value if set, zero value otherwise.
func (o *StatisticsDetailstatsResponseDataInner) GetVirusinfo() string {
	if o == nil || IsNil(o.Virusinfo) {
		var ret string
		return ret
	}
	return *o.Virusinfo
}

// GetVirusinfoOk returns a tuple with the Virusinfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsDetailstatsResponseDataInner) GetVirusinfoOk() (*string, bool) {
	if o == nil || IsNil(o.Virusinfo) {
		return nil, false
	}
	return o.Virusinfo, true
}

// HasVirusinfo returns a boolean if a field has been set.
func (o *StatisticsDetailstatsResponseDataInner) HasVirusinfo() bool {
	if o != nil && !IsNil(o.Virusinfo) {
		return true
	}

	return false
}

// SetVirusinfo gets a reference to the given string and assigns it to the Virusinfo field.
func (o *StatisticsDetailstatsResponseDataInner) SetVirusinfo(v string) {
	o.Virusinfo = &v
}


func (o StatisticsDetailstatsResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsDetailstatsResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["blocked"] = o.Blocked
	
	toSerialize["bytes"] = o.Bytes
	
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	
	toSerialize["spamlevel"] = o.Spamlevel
	
	toSerialize["time"] = o.Time
	
	if !IsNil(o.Virusinfo) {
		toSerialize["virusinfo"] = o.Virusinfo
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatisticsDetailstatsResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blocked",
		"bytes",
		"spamlevel",
		"time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatisticsDetailstatsResponseDataInner := _StatisticsDetailstatsResponseDataInner{}

	err = json.Unmarshal(data, &varStatisticsDetailstatsResponseDataInner)

	if err != nil {
		return err
	}

	*o = StatisticsDetailstatsResponseDataInner(varStatisticsDetailstatsResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "blocked")
		delete(additionalProperties, "bytes")
		delete(additionalProperties, "receiver")
		delete(additionalProperties, "sender")
		delete(additionalProperties, "spamlevel")
		delete(additionalProperties, "time")
		delete(additionalProperties, "virusinfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatisticsDetailstatsResponseDataInner struct {
	value *StatisticsDetailstatsResponseDataInner
	isSet bool
}

func (v NullableStatisticsDetailstatsResponseDataInner) Get() *StatisticsDetailstatsResponseDataInner {
	return v.value
}

func (v *NullableStatisticsDetailstatsResponseDataInner) Set(val *StatisticsDetailstatsResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsDetailstatsResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsDetailstatsResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsDetailstatsResponseDataInner(val *StatisticsDetailstatsResponseDataInner) *NullableStatisticsDetailstatsResponseDataInner {
	return &NullableStatisticsDetailstatsResponseDataInner{value: val, isSet: true}
}

func (v NullableStatisticsDetailstatsResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsDetailstatsResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


