/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessUsersGetUsersResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessUsersGetUsersResponseDataInner{}

// AccessUsersGetUsersResponseDataInner struct for AccessUsersGetUsersResponseDataInner
type AccessUsersGetUsersResponseDataInner struct {

	Comment *string `json:"comment,omitempty"`

	Enable PmgBoolean `json:"enable"`

	Role string `json:"role"`

	// Contains a timestamp until when a user is locked out of 2nd factors.
	TfaLockedUntil *int64 `json:"tfa-locked-until,omitempty"`

	// True if the user is currently locked out of TOTP factors.
	TotpLocked *PmgBoolean `json:"totp-locked,omitempty"`

	Userid string `json:"userid"`

	AdditionalProperties map[string]interface{}
}

type _AccessUsersGetUsersResponseDataInner AccessUsersGetUsersResponseDataInner

// NewAccessUsersGetUsersResponseDataInner instantiates a new AccessUsersGetUsersResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessUsersGetUsersResponseDataInner(enable PmgBoolean, role string, userid string) *AccessUsersGetUsersResponseDataInner {
	this := AccessUsersGetUsersResponseDataInner{}
	this.Enable = enable
	this.Role = role
	this.Userid = userid
	return &this
}

// NewAccessUsersGetUsersResponseDataInnerWithDefaults instantiates a new AccessUsersGetUsersResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessUsersGetUsersResponseDataInnerWithDefaults() *AccessUsersGetUsersResponseDataInner {
	this := AccessUsersGetUsersResponseDataInner{}







	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AccessUsersGetUsersResponseDataInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AccessUsersGetUsersResponseDataInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AccessUsersGetUsersResponseDataInner) SetComment(v string) {
	o.Comment = &v
}


// GetEnable returns the Enable field value
func (o *AccessUsersGetUsersResponseDataInner) GetEnable() PmgBoolean {
	if o == nil {
		var ret PmgBoolean
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetEnableOk() (*PmgBoolean, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *AccessUsersGetUsersResponseDataInner) SetEnable(v PmgBoolean) {
	o.Enable = v
}


// GetRole returns the Role field value
func (o *AccessUsersGetUsersResponseDataInner) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *AccessUsersGetUsersResponseDataInner) SetRole(v string) {
	o.Role = v
}


// GetTfaLockedUntil returns the TfaLockedUntil field value if set, zero value otherwise.
func (o *AccessUsersGetUsersResponseDataInner) GetTfaLockedUntil() int64 {
	if o == nil || IsNil(o.TfaLockedUntil) {
		var ret int64
		return ret
	}
	return *o.TfaLockedUntil
}

// GetTfaLockedUntilOk returns a tuple with the TfaLockedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetTfaLockedUntilOk() (*int64, bool) {
	if o == nil || IsNil(o.TfaLockedUntil) {
		return nil, false
	}
	return o.TfaLockedUntil, true
}

// HasTfaLockedUntil returns a boolean if a field has been set.
func (o *AccessUsersGetUsersResponseDataInner) HasTfaLockedUntil() bool {
	if o != nil && !IsNil(o.TfaLockedUntil) {
		return true
	}

	return false
}

// SetTfaLockedUntil gets a reference to the given int64 and assigns it to the TfaLockedUntil field.
func (o *AccessUsersGetUsersResponseDataInner) SetTfaLockedUntil(v int64) {
	o.TfaLockedUntil = &v
}


// GetTotpLocked returns the TotpLocked field value if set, zero value otherwise.
func (o *AccessUsersGetUsersResponseDataInner) GetTotpLocked() PmgBoolean {
	if o == nil || IsNil(o.TotpLocked) {
		var ret PmgBoolean
		return ret
	}
	return *o.TotpLocked
}

// GetTotpLockedOk returns a tuple with the TotpLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetTotpLockedOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.TotpLocked) {
		return nil, false
	}
	return o.TotpLocked, true
}

// HasTotpLocked returns a boolean if a field has been set.
func (o *AccessUsersGetUsersResponseDataInner) HasTotpLocked() bool {
	if o != nil && !IsNil(o.TotpLocked) {
		return true
	}

	return false
}

// SetTotpLocked gets a reference to the given PmgBoolean and assigns it to the TotpLocked field.
func (o *AccessUsersGetUsersResponseDataInner) SetTotpLocked(v PmgBoolean) {
	o.TotpLocked = &v
}


// GetUserid returns the Userid field value
func (o *AccessUsersGetUsersResponseDataInner) GetUserid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userid
}

// GetUseridOk returns a tuple with the Userid field value
// and a boolean to check if the value has been set.
func (o *AccessUsersGetUsersResponseDataInner) GetUseridOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userid, true
}

// SetUserid sets field value
func (o *AccessUsersGetUsersResponseDataInner) SetUserid(v string) {
	o.Userid = v
}


func (o AccessUsersGetUsersResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessUsersGetUsersResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	toSerialize["enable"] = o.Enable
	
	toSerialize["role"] = o.Role
	
	if !IsNil(o.TfaLockedUntil) {
		toSerialize["tfa-locked-until"] = o.TfaLockedUntil
	}
	
	if !IsNil(o.TotpLocked) {
		toSerialize["totp-locked"] = o.TotpLocked
	}
	
	toSerialize["userid"] = o.Userid
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccessUsersGetUsersResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enable",
		"role",
		"userid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessUsersGetUsersResponseDataInner := _AccessUsersGetUsersResponseDataInner{}

	err = json.Unmarshal(data, &varAccessUsersGetUsersResponseDataInner)

	if err != nil {
		return err
	}

	*o = AccessUsersGetUsersResponseDataInner(varAccessUsersGetUsersResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "comment")
		delete(additionalProperties, "enable")
		delete(additionalProperties, "role")
		delete(additionalProperties, "tfa-locked-until")
		delete(additionalProperties, "totp-locked")
		delete(additionalProperties, "userid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccessUsersGetUsersResponseDataInner struct {
	value *AccessUsersGetUsersResponseDataInner
	isSet bool
}

func (v NullableAccessUsersGetUsersResponseDataInner) Get() *AccessUsersGetUsersResponseDataInner {
	return v.value
}

func (v *NullableAccessUsersGetUsersResponseDataInner) Set(val *AccessUsersGetUsersResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessUsersGetUsersResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessUsersGetUsersResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessUsersGetUsersResponseDataInner(val *AccessUsersGetUsersResponseDataInner) *NullableAccessUsersGetUsersResponseDataInner {
	return &NullableAccessUsersGetUsersResponseDataInner{value: val, isSet: true}
}

func (v NullableAccessUsersGetUsersResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessUsersGetUsersResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


