/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgModeEnum the model 'PmgModeEnum'
type PmgModeEnum string

// List of PmgModeEnum
const (
	PMGMODEENUM_LDAP PmgModeEnum = "ldap"
	PMGMODEENUM_LDAPS PmgModeEnum = "ldaps"
	PMGMODEENUM_LDAPSTARTTLS PmgModeEnum = "ldap+starttls"
)

// All allowed values of PmgModeEnum enum
var AllowedPmgModeEnumEnumValues = []PmgModeEnum{
	"ldap",
	"ldaps",
	"ldap+starttls",
}

func (v *PmgModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgModeEnum(value)
	for _, existing := range AllowedPmgModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgModeEnum", value)
}

// NewPmgModeEnumFromValue returns a pointer to a valid PmgModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgModeEnumFromValue(v string) (*PmgModeEnum, error) {
	ev := PmgModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgModeEnum: valid values are %v", v, AllowedPmgModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgModeEnum) IsValid() bool {
	for _, existing := range AllowedPmgModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgModeEnum value
func (v PmgModeEnum) Ptr() *PmgModeEnum {
	return &v
}

type NullablePmgModeEnum struct {
	value *PmgModeEnum
	isSet bool
}

func (v NullablePmgModeEnum) Get() *PmgModeEnum {
	return v.value
}

func (v *NullablePmgModeEnum) Set(val *PmgModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgModeEnum(val *PmgModeEnum) *NullablePmgModeEnum {
	return &NullablePmgModeEnum{value: val, isSet: true}
}

func (v NullablePmgModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

