/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PmgAutocreateRoleAssignmentField - struct for PmgAutocreateRoleAssignmentField
type PmgAutocreateRoleAssignmentField struct {
	PmgAutocreateRoleAssignmentConfig *PmgAutocreateRoleAssignmentConfig
	String *string
}

// PmgAutocreateRoleAssignmentConfigAsPmgAutocreateRoleAssignmentField is a convenience function that returns PmgAutocreateRoleAssignmentConfig wrapped in PmgAutocreateRoleAssignmentField
func PmgAutocreateRoleAssignmentConfigAsPmgAutocreateRoleAssignmentField(v *PmgAutocreateRoleAssignmentConfig) PmgAutocreateRoleAssignmentField {
	return PmgAutocreateRoleAssignmentField{
		PmgAutocreateRoleAssignmentConfig: v,
	}
}

// stringAsPmgAutocreateRoleAssignmentField is a convenience function that returns string wrapped in PmgAutocreateRoleAssignmentField
func StringAsPmgAutocreateRoleAssignmentField(v *string) PmgAutocreateRoleAssignmentField {
	return PmgAutocreateRoleAssignmentField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PmgAutocreateRoleAssignmentField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PmgAutocreateRoleAssignmentConfig
	err = newStrictDecoder(data).Decode(&dst.PmgAutocreateRoleAssignmentConfig)
	if err == nil {
		jsonPmgAutocreateRoleAssignmentConfig, _ := json.Marshal(dst.PmgAutocreateRoleAssignmentConfig)
		if string(jsonPmgAutocreateRoleAssignmentConfig) == "{}" { // empty struct
			dst.PmgAutocreateRoleAssignmentConfig = nil
		} else {
			if err = validator.Validate(dst.PmgAutocreateRoleAssignmentConfig); err != nil {
				dst.PmgAutocreateRoleAssignmentConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PmgAutocreateRoleAssignmentConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PmgAutocreateRoleAssignmentConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PmgAutocreateRoleAssignmentField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PmgAutocreateRoleAssignmentField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PmgAutocreateRoleAssignmentField) MarshalJSON() ([]byte, error) {
	if src.PmgAutocreateRoleAssignmentConfig != nil {
		return json.Marshal(&src.PmgAutocreateRoleAssignmentConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PmgAutocreateRoleAssignmentField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PmgAutocreateRoleAssignmentConfig != nil {
		return obj.PmgAutocreateRoleAssignmentConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PmgAutocreateRoleAssignmentField) GetActualInstanceValue() (interface{}) {
	if obj.PmgAutocreateRoleAssignmentConfig != nil {
		return *obj.PmgAutocreateRoleAssignmentConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePmgAutocreateRoleAssignmentField struct {
	value *PmgAutocreateRoleAssignmentField
	isSet bool
}

func (v NullablePmgAutocreateRoleAssignmentField) Get() *PmgAutocreateRoleAssignmentField {
	return v.value
}

func (v *NullablePmgAutocreateRoleAssignmentField) Set(val *PmgAutocreateRoleAssignmentField) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgAutocreateRoleAssignmentField) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgAutocreateRoleAssignmentField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgAutocreateRoleAssignmentField(val *PmgAutocreateRoleAssignmentField) *NullablePmgAutocreateRoleAssignmentField {
	return &NullablePmgAutocreateRoleAssignmentField{value: val, isSet: true}
}

func (v NullablePmgAutocreateRoleAssignmentField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgAutocreateRoleAssignmentField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


