/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigRuledbRemoveattachmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigRuledbRemoveattachmentsRequest{}

// ConfigRuledbRemoveattachmentsRequest struct for ConfigRuledbRemoveattachmentsRequest
type ConfigRuledbRemoveattachmentsRequest struct {

	// Remove all attachments
	All *PmgBoolean `json:"all,omitempty"`

	// Informational comment.
	Info *string `json:"info,omitempty"`

	// Action name.
	Name string `json:"name"`

	// Copy original mail to attachment Quarantine.
	Quarantine *PmgBoolean `json:"quarantine,omitempty"`

	// The replacement text.
	Text string `json:"text"`

}

type _ConfigRuledbRemoveattachmentsRequest ConfigRuledbRemoveattachmentsRequest

// NewConfigRuledbRemoveattachmentsRequest instantiates a new ConfigRuledbRemoveattachmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigRuledbRemoveattachmentsRequest(name string, text string) *ConfigRuledbRemoveattachmentsRequest {
	this := ConfigRuledbRemoveattachmentsRequest{}
	this.Name = name
	var quarantine PmgBoolean = PMGBOOLEAN__0
	this.Quarantine = &quarantine
	this.Text = text
	return &this
}

// NewConfigRuledbRemoveattachmentsRequestWithDefaults instantiates a new ConfigRuledbRemoveattachmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigRuledbRemoveattachmentsRequestWithDefaults() *ConfigRuledbRemoveattachmentsRequest {
	this := ConfigRuledbRemoveattachmentsRequest{}




	var quarantine PmgBoolean = PMGBOOLEAN__0
	this.Quarantine = &quarantine


	return &this
}


// GetAll returns the All field value if set, zero value otherwise.
func (o *ConfigRuledbRemoveattachmentsRequest) GetAll() PmgBoolean {
	if o == nil || IsNil(o.All) {
		var ret PmgBoolean
		return ret
	}
	return *o.All
}

// GetAllOk returns a tuple with the All field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) GetAllOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.All) {
		return nil, false
	}
	return o.All, true
}

// HasAll returns a boolean if a field has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) HasAll() bool {
	if o != nil && !IsNil(o.All) {
		return true
	}

	return false
}

// SetAll gets a reference to the given PmgBoolean and assigns it to the All field.
func (o *ConfigRuledbRemoveattachmentsRequest) SetAll(v PmgBoolean) {
	o.All = &v
}


// GetInfo returns the Info field value if set, zero value otherwise.
func (o *ConfigRuledbRemoveattachmentsRequest) GetInfo() string {
	if o == nil || IsNil(o.Info) {
		var ret string
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) GetInfoOk() (*string, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given string and assigns it to the Info field.
func (o *ConfigRuledbRemoveattachmentsRequest) SetInfo(v string) {
	o.Info = &v
}


// GetName returns the Name field value
func (o *ConfigRuledbRemoveattachmentsRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigRuledbRemoveattachmentsRequest) SetName(v string) {
	o.Name = v
}


// GetQuarantine returns the Quarantine field value if set, zero value otherwise.
func (o *ConfigRuledbRemoveattachmentsRequest) GetQuarantine() PmgBoolean {
	if o == nil || IsNil(o.Quarantine) {
		var ret PmgBoolean
		return ret
	}
	return *o.Quarantine
}

// GetQuarantineOk returns a tuple with the Quarantine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) GetQuarantineOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Quarantine) {
		return nil, false
	}
	return o.Quarantine, true
}

// HasQuarantine returns a boolean if a field has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) HasQuarantine() bool {
	if o != nil && !IsNil(o.Quarantine) {
		return true
	}

	return false
}

// SetQuarantine gets a reference to the given PmgBoolean and assigns it to the Quarantine field.
func (o *ConfigRuledbRemoveattachmentsRequest) SetQuarantine(v PmgBoolean) {
	o.Quarantine = &v
}


// GetText returns the Text field value
func (o *ConfigRuledbRemoveattachmentsRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ConfigRuledbRemoveattachmentsRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ConfigRuledbRemoveattachmentsRequest) SetText(v string) {
	o.Text = v
}


func (o ConfigRuledbRemoveattachmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigRuledbRemoveattachmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.All) {
		toSerialize["all"] = o.All
	}
	
	if !IsNil(o.Info) {
		toSerialize["info"] = o.Info
	}
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Quarantine) {
		toSerialize["quarantine"] = o.Quarantine
	}
	
	toSerialize["text"] = o.Text
	
	return toSerialize, nil
}

func (o *ConfigRuledbRemoveattachmentsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigRuledbRemoveattachmentsRequest := _ConfigRuledbRemoveattachmentsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigRuledbRemoveattachmentsRequest)

	if err != nil {
		return err
	}

	*o = ConfigRuledbRemoveattachmentsRequest(varConfigRuledbRemoveattachmentsRequest)

	return err
}

type NullableConfigRuledbRemoveattachmentsRequest struct {
	value *ConfigRuledbRemoveattachmentsRequest
	isSet bool
}

func (v NullableConfigRuledbRemoveattachmentsRequest) Get() *ConfigRuledbRemoveattachmentsRequest {
	return v.value
}

func (v *NullableConfigRuledbRemoveattachmentsRequest) Set(val *ConfigRuledbRemoveattachmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigRuledbRemoveattachmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigRuledbRemoveattachmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigRuledbRemoveattachmentsRequest(val *ConfigRuledbRemoveattachmentsRequest) *NullableConfigRuledbRemoveattachmentsRequest {
	return &NullableConfigRuledbRemoveattachmentsRequest{value: val, isSet: true}
}

func (v NullableConfigRuledbRemoveattachmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigRuledbRemoveattachmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


