/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgBondModeEnum the model 'PmgBondModeEnum'
type PmgBondModeEnum string

// List of PmgBondModeEnum
const (
	PMGBONDMODEENUM_BALANCE_RR PmgBondModeEnum = "balance-rr"
	PMGBONDMODEENUM_ACTIVE_BACKUP PmgBondModeEnum = "active-backup"
	PMGBONDMODEENUM_BALANCE_XOR PmgBondModeEnum = "balance-xor"
	PMGBONDMODEENUM_BROADCAST PmgBondModeEnum = "broadcast"
	PMGBONDMODEENUM__802_3AD PmgBondModeEnum = "802.3ad"
	PMGBONDMODEENUM_BALANCE_TLB PmgBondModeEnum = "balance-tlb"
	PMGBONDMODEENUM_BALANCE_ALB PmgBondModeEnum = "balance-alb"
	PMGBONDMODEENUM_BALANCE_SLB PmgBondModeEnum = "balance-slb"
	PMGBONDMODEENUM_LACP_BALANCE_SLB PmgBondModeEnum = "lacp-balance-slb"
	PMGBONDMODEENUM_LACP_BALANCE_TCP PmgBondModeEnum = "lacp-balance-tcp"
)

// All allowed values of PmgBondModeEnum enum
var AllowedPmgBondModeEnumEnumValues = []PmgBondModeEnum{
	"balance-rr",
	"active-backup",
	"balance-xor",
	"broadcast",
	"802.3ad",
	"balance-tlb",
	"balance-alb",
	"balance-slb",
	"lacp-balance-slb",
	"lacp-balance-tcp",
}

func (v *PmgBondModeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgBondModeEnum(value)
	for _, existing := range AllowedPmgBondModeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgBondModeEnum", value)
}

// NewPmgBondModeEnumFromValue returns a pointer to a valid PmgBondModeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgBondModeEnumFromValue(v string) (*PmgBondModeEnum, error) {
	ev := PmgBondModeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgBondModeEnum: valid values are %v", v, AllowedPmgBondModeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgBondModeEnum) IsValid() bool {
	for _, existing := range AllowedPmgBondModeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgBondModeEnum value
func (v PmgBondModeEnum) Ptr() *PmgBondModeEnum {
	return &v
}

type NullablePmgBondModeEnum struct {
	value *PmgBondModeEnum
	isSet bool
}

func (v NullablePmgBondModeEnum) Get() *PmgBondModeEnum {
	return v.value
}

func (v *NullablePmgBondModeEnum) Set(val *PmgBondModeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgBondModeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgBondModeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgBondModeEnum(val *PmgBondModeEnum) *NullablePmgBondModeEnum {
	return &NullablePmgBondModeEnum{value: val, isSet: true}
}

func (v NullablePmgBondModeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgBondModeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

