/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest{}

// ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest struct for ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest
type ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest struct {

	// Domain for which TLS should be enforced on incoming connections
	Domain string `json:"domain"`

}

type _ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest

// NewConfigTlsInboundDomainsCreateTlsInboundDomainsRequest instantiates a new ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigTlsInboundDomainsCreateTlsInboundDomainsRequest(domain string) *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest {
	this := ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest{}
	this.Domain = domain
	return &this
}

// NewConfigTlsInboundDomainsCreateTlsInboundDomainsRequestWithDefaults instantiates a new ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigTlsInboundDomainsCreateTlsInboundDomainsRequestWithDefaults() *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest {
	this := ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest{}


	return &this
}


// GetDomain returns the Domain field value
func (o *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) SetDomain(v string) {
	o.Domain = v
}


func (o ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["domain"] = o.Domain
	
	return toSerialize, nil
}

func (o *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigTlsInboundDomainsCreateTlsInboundDomainsRequest := _ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigTlsInboundDomainsCreateTlsInboundDomainsRequest)

	if err != nil {
		return err
	}

	*o = ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest(varConfigTlsInboundDomainsCreateTlsInboundDomainsRequest)

	return err
}

type NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest struct {
	value *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest
	isSet bool
}

func (v NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) Get() *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest {
	return v.value
}

func (v *NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) Set(val *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest(val *ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) *NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest {
	return &NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest{value: val, isSet: true}
}

func (v NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


