/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PmgAcmeField - struct for PmgAcmeField
type PmgAcmeField struct {
	PmgAcmeConfig *PmgAcmeConfig
	String *string
}

// PmgAcmeConfigAsPmgAcmeField is a convenience function that returns PmgAcmeConfig wrapped in PmgAcmeField
func PmgAcmeConfigAsPmgAcmeField(v *PmgAcmeConfig) PmgAcmeField {
	return PmgAcmeField{
		PmgAcmeConfig: v,
	}
}

// stringAsPmgAcmeField is a convenience function that returns string wrapped in PmgAcmeField
func StringAsPmgAcmeField(v *string) PmgAcmeField {
	return PmgAcmeField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PmgAcmeField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PmgAcmeConfig
	err = newStrictDecoder(data).Decode(&dst.PmgAcmeConfig)
	if err == nil {
		jsonPmgAcmeConfig, _ := json.Marshal(dst.PmgAcmeConfig)
		if string(jsonPmgAcmeConfig) == "{}" { // empty struct
			dst.PmgAcmeConfig = nil
		} else {
			if err = validator.Validate(dst.PmgAcmeConfig); err != nil {
				dst.PmgAcmeConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PmgAcmeConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PmgAcmeConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PmgAcmeField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PmgAcmeField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PmgAcmeField) MarshalJSON() ([]byte, error) {
	if src.PmgAcmeConfig != nil {
		return json.Marshal(&src.PmgAcmeConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PmgAcmeField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PmgAcmeConfig != nil {
		return obj.PmgAcmeConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PmgAcmeField) GetActualInstanceValue() (interface{}) {
	if obj.PmgAcmeConfig != nil {
		return *obj.PmgAcmeConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePmgAcmeField struct {
	value *PmgAcmeField
	isSet bool
}

func (v NullablePmgAcmeField) Get() *PmgAcmeField {
	return v.value
}

func (v *NullablePmgAcmeField) Set(val *PmgAcmeField) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgAcmeField) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgAcmeField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgAcmeField(val *PmgAcmeField) *NullablePmgAcmeField {
	return &NullablePmgAcmeField{value: val, isSet: true}
}

func (v NullablePmgAcmeField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgAcmeField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


