/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigMynetworksReadGetMynetworksResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigMynetworksReadGetMynetworksResponseData{}

// ConfigMynetworksReadGetMynetworksResponseData struct for ConfigMynetworksReadGetMynetworksResponseData
type ConfigMynetworksReadGetMynetworksResponseData struct {

	Cidr string `json:"cidr"`

	Comment string `json:"comment"`

	AdditionalProperties map[string]interface{}
}

type _ConfigMynetworksReadGetMynetworksResponseData ConfigMynetworksReadGetMynetworksResponseData

// NewConfigMynetworksReadGetMynetworksResponseData instantiates a new ConfigMynetworksReadGetMynetworksResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigMynetworksReadGetMynetworksResponseData(cidr string, comment string) *ConfigMynetworksReadGetMynetworksResponseData {
	this := ConfigMynetworksReadGetMynetworksResponseData{}
	this.Cidr = cidr
	this.Comment = comment
	return &this
}

// NewConfigMynetworksReadGetMynetworksResponseDataWithDefaults instantiates a new ConfigMynetworksReadGetMynetworksResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigMynetworksReadGetMynetworksResponseDataWithDefaults() *ConfigMynetworksReadGetMynetworksResponseData {
	this := ConfigMynetworksReadGetMynetworksResponseData{}



	return &this
}


// GetCidr returns the Cidr field value
func (o *ConfigMynetworksReadGetMynetworksResponseData) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *ConfigMynetworksReadGetMynetworksResponseData) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *ConfigMynetworksReadGetMynetworksResponseData) SetCidr(v string) {
	o.Cidr = v
}


// GetComment returns the Comment field value
func (o *ConfigMynetworksReadGetMynetworksResponseData) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *ConfigMynetworksReadGetMynetworksResponseData) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *ConfigMynetworksReadGetMynetworksResponseData) SetComment(v string) {
	o.Comment = v
}


func (o ConfigMynetworksReadGetMynetworksResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigMynetworksReadGetMynetworksResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["cidr"] = o.Cidr
	
	toSerialize["comment"] = o.Comment
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigMynetworksReadGetMynetworksResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cidr",
		"comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigMynetworksReadGetMynetworksResponseData := _ConfigMynetworksReadGetMynetworksResponseData{}

	err = json.Unmarshal(data, &varConfigMynetworksReadGetMynetworksResponseData)

	if err != nil {
		return err
	}

	*o = ConfigMynetworksReadGetMynetworksResponseData(varConfigMynetworksReadGetMynetworksResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cidr")
		delete(additionalProperties, "comment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigMynetworksReadGetMynetworksResponseData struct {
	value *ConfigMynetworksReadGetMynetworksResponseData
	isSet bool
}

func (v NullableConfigMynetworksReadGetMynetworksResponseData) Get() *ConfigMynetworksReadGetMynetworksResponseData {
	return v.value
}

func (v *NullableConfigMynetworksReadGetMynetworksResponseData) Set(val *ConfigMynetworksReadGetMynetworksResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigMynetworksReadGetMynetworksResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigMynetworksReadGetMynetworksResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigMynetworksReadGetMynetworksResponseData(val *ConfigMynetworksReadGetMynetworksResponseData) *NullableConfigMynetworksReadGetMynetworksResponseData {
	return &NullableConfigMynetworksReadGetMynetworksResponseData{value: val, isSet: true}
}

func (v NullableConfigMynetworksReadGetMynetworksResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigMynetworksReadGetMynetworksResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


