/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QuarantineContentActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuarantineContentActionRequest{}

// QuarantineContentActionRequest struct for QuarantineContentActionRequest
type QuarantineContentActionRequest struct {

	// Action - specify what you want to do with the mail.
	Action PmgQuarantineContentActionEnum `json:"action"`

	// Unique IDs, separate with ;
	Id string `json:"id" validate:"regexp=C\\\\d+R\\\\d+T\\\\d+(;C\\\\d+R\\\\d+T\\\\d+)*"`

}

type _QuarantineContentActionRequest QuarantineContentActionRequest

// NewQuarantineContentActionRequest instantiates a new QuarantineContentActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuarantineContentActionRequest(action PmgQuarantineContentActionEnum, id string) *QuarantineContentActionRequest {
	this := QuarantineContentActionRequest{}
	this.Action = action
	this.Id = id
	return &this
}

// NewQuarantineContentActionRequestWithDefaults instantiates a new QuarantineContentActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuarantineContentActionRequestWithDefaults() *QuarantineContentActionRequest {
	this := QuarantineContentActionRequest{}



	return &this
}


// GetAction returns the Action field value
func (o *QuarantineContentActionRequest) GetAction() PmgQuarantineContentActionEnum {
	if o == nil {
		var ret PmgQuarantineContentActionEnum
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *QuarantineContentActionRequest) GetActionOk() (*PmgQuarantineContentActionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *QuarantineContentActionRequest) SetAction(v PmgQuarantineContentActionEnum) {
	o.Action = v
}


// GetId returns the Id field value
func (o *QuarantineContentActionRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QuarantineContentActionRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QuarantineContentActionRequest) SetId(v string) {
	o.Id = v
}


func (o QuarantineContentActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuarantineContentActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["action"] = o.Action
	
	toSerialize["id"] = o.Id
	
	return toSerialize, nil
}

func (o *QuarantineContentActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuarantineContentActionRequest := _QuarantineContentActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuarantineContentActionRequest)

	if err != nil {
		return err
	}

	*o = QuarantineContentActionRequest(varQuarantineContentActionRequest)

	return err
}

type NullableQuarantineContentActionRequest struct {
	value *QuarantineContentActionRequest
	isSet bool
}

func (v NullableQuarantineContentActionRequest) Get() *QuarantineContentActionRequest {
	return v.value
}

func (v *NullableQuarantineContentActionRequest) Set(val *QuarantineContentActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuarantineContentActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuarantineContentActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuarantineContentActionRequest(val *QuarantineContentActionRequest) *NullableQuarantineContentActionRequest {
	return &NullableQuarantineContentActionRequest{value: val, isSet: true}
}

func (v NullableQuarantineContentActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuarantineContentActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


