/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PmgConfigSpamquarReportstyleEnum the model 'PmgConfigSpamquarReportstyleEnum'
type PmgConfigSpamquarReportstyleEnum string

// List of PmgConfigSpamquarReportstyleEnum
const (
	PMGCONFIGSPAMQUARREPORTSTYLEENUM_NONE PmgConfigSpamquarReportstyleEnum = "none"
	PMGCONFIGSPAMQUARREPORTSTYLEENUM_SHORT PmgConfigSpamquarReportstyleEnum = "short"
	PMGCONFIGSPAMQUARREPORTSTYLEENUM_VERBOSE PmgConfigSpamquarReportstyleEnum = "verbose"
	PMGCONFIGSPAMQUARREPORTSTYLEENUM_CUSTOM PmgConfigSpamquarReportstyleEnum = "custom"
)

// All allowed values of PmgConfigSpamquarReportstyleEnum enum
var AllowedPmgConfigSpamquarReportstyleEnumEnumValues = []PmgConfigSpamquarReportstyleEnum{
	"none",
	"short",
	"verbose",
	"custom",
}

func (v *PmgConfigSpamquarReportstyleEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PmgConfigSpamquarReportstyleEnum(value)
	for _, existing := range AllowedPmgConfigSpamquarReportstyleEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PmgConfigSpamquarReportstyleEnum", value)
}

// NewPmgConfigSpamquarReportstyleEnumFromValue returns a pointer to a valid PmgConfigSpamquarReportstyleEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPmgConfigSpamquarReportstyleEnumFromValue(v string) (*PmgConfigSpamquarReportstyleEnum, error) {
	ev := PmgConfigSpamquarReportstyleEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PmgConfigSpamquarReportstyleEnum: valid values are %v", v, AllowedPmgConfigSpamquarReportstyleEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PmgConfigSpamquarReportstyleEnum) IsValid() bool {
	for _, existing := range AllowedPmgConfigSpamquarReportstyleEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PmgConfigSpamquarReportstyleEnum value
func (v PmgConfigSpamquarReportstyleEnum) Ptr() *PmgConfigSpamquarReportstyleEnum {
	return &v
}

type NullablePmgConfigSpamquarReportstyleEnum struct {
	value *PmgConfigSpamquarReportstyleEnum
	isSet bool
}

func (v NullablePmgConfigSpamquarReportstyleEnum) Get() *PmgConfigSpamquarReportstyleEnum {
	return v.value
}

func (v *NullablePmgConfigSpamquarReportstyleEnum) Set(val *PmgConfigSpamquarReportstyleEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePmgConfigSpamquarReportstyleEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePmgConfigSpamquarReportstyleEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePmgConfigSpamquarReportstyleEnum(val *PmgConfigSpamquarReportstyleEnum) *NullablePmgConfigSpamquarReportstyleEnum {
	return &NullablePmgConfigSpamquarReportstyleEnum{value: val, isSet: true}
}

func (v NullablePmgConfigSpamquarReportstyleEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePmgConfigSpamquarReportstyleEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

