/*
Proxmox Mail Gateway API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigAdminUpdateAdminSectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAdminUpdateAdminSectionRequest{}

// ConfigAdminUpdateAdminSectionRequest struct for ConfigAdminUpdateAdminSectionRequest
type ConfigAdminUpdateAdminSectionRequest struct {

	// Text for 'From' header in admin mails and bounces.
	AdminMailFrom *string `json:"admin-mail-from,omitempty" validate:"regexp=^\\\\p{PosixPrint}{1,998}$"`

	// Enable advanced filters for statistic.  If this is enabled, the receiver statistic are limited to active ones (receivers which also sent out mail in the 90 days before), and the contact statistic will not contain these active receivers. 
	Advfilter *PmgBoolean `json:"advfilter,omitempty"`

	// Use Avast Virus Scanner (/usr/bin/scan). You need to buy and install 'Avast Core Security' before you can enable this feature.
	Avast *PmgBoolean `json:"avast,omitempty"`

	// Use ClamAV Virus Scanner. This is the default virus scanner and is enabled by default.
	Clamav *PmgBoolean `json:"clamav,omitempty"`

	// Use Custom Check Script. The script has to take the defined arguments and can return Virus findings or a Spamscore.
	CustomCheck *PmgBoolean `json:"custom_check,omitempty"`

	// Absolute Path to the Custom Check Script
	CustomCheckPath *string `json:"custom_check_path,omitempty" validate:"regexp=^\\/([^\\/\\\\0]+\\/)+[^\\/\\\\0]+$"`

	// Send daily reports.
	Dailyreport *PmgBoolean `json:"dailyreport,omitempty"`

	// A list of settings you want to delete.
	Delete *string `json:"delete,omitempty"`

	// Demo mode - do not start SMTP filter.
	Demo *PmgBoolean `json:"demo,omitempty"`

	// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`

	// Whether to sign using the domain found in the header or the envelope.
	DkimUseDomain *PmgConfigAdminDkimUseDomainEnum `json:"dkim-use-domain,omitempty"`

	// Default DKIM selector
	DkimSelector *string `json:"dkim_selector,omitempty" validate:"regexp=^(?:[A-Za-z0-9](?:[A-Za-z0-9\\\\-]*[A-Za-z0-9])?)(?:\\\\.[A-Za-z0-9](?:[A-Za-z0-9\\\\-]*[A-Za-z0-9])?)*$"`

	// DKIM sign outbound mails with the configured Selector.
	DkimSign *PmgBoolean `json:"dkim_sign,omitempty"`

	// DKIM sign all outgoing mails irrespective of the Envelope From domain.
	DkimSignAllMail *PmgBoolean `json:"dkim_sign_all_mail,omitempty"`

	// Administrator E-Mail address.
	Email *string `json:"email,omitempty" validate:"regexp=^[^\\\\s@]+@[^\\\\s@]+\\\\.[^\\\\s@]+$"`

	// Specify external http proxy which is used for downloads (example: 'http://username:password@host:port/')
	HttpProxy *string `json:"http_proxy,omitempty" validate:"regexp=http:\\/\\/.*"`

	// User Statistics Lifetime (days)
	Statlifetime *int64 `json:"statlifetime,omitempty"`

}

// NewConfigAdminUpdateAdminSectionRequest instantiates a new ConfigAdminUpdateAdminSectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAdminUpdateAdminSectionRequest() *ConfigAdminUpdateAdminSectionRequest {
	this := ConfigAdminUpdateAdminSectionRequest{}
	var adminMailFrom string = "Proxmox Mail Gateway <postmaster>"
	this.AdminMailFrom = &adminMailFrom
	var advfilter PmgBoolean = PMGBOOLEAN__0
	this.Advfilter = &advfilter
	var avast PmgBoolean = PMGBOOLEAN__0
	this.Avast = &avast
	var clamav PmgBoolean = PMGBOOLEAN__1
	this.Clamav = &clamav
	var customCheck PmgBoolean = PMGBOOLEAN__0
	this.CustomCheck = &customCheck
	var customCheckPath string = "/usr/local/bin/pmg-custom-check"
	this.CustomCheckPath = &customCheckPath
	var dailyreport PmgBoolean = PMGBOOLEAN__1
	this.Dailyreport = &dailyreport
	var demo PmgBoolean = PMGBOOLEAN__0
	this.Demo = &demo
	var dkimUseDomain PmgConfigAdminDkimUseDomainEnum = PMGCONFIGADMINDKIMUSEDOMAINENUM_ENVELOPE
	this.DkimUseDomain = &dkimUseDomain
	var dkimSign PmgBoolean = PMGBOOLEAN__0
	this.DkimSign = &dkimSign
	var dkimSignAllMail PmgBoolean = PMGBOOLEAN__0
	this.DkimSignAllMail = &dkimSignAllMail
	var email string = "admin@domain.tld"
	this.Email = &email
	var statlifetime int64 = 7
	this.Statlifetime = &statlifetime
	return &this
}

// NewConfigAdminUpdateAdminSectionRequestWithDefaults instantiates a new ConfigAdminUpdateAdminSectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAdminUpdateAdminSectionRequestWithDefaults() *ConfigAdminUpdateAdminSectionRequest {
	this := ConfigAdminUpdateAdminSectionRequest{}

	var adminMailFrom string = "Proxmox Mail Gateway <postmaster>"
	this.AdminMailFrom = &adminMailFrom

	var advfilter PmgBoolean = PMGBOOLEAN__0
	this.Advfilter = &advfilter

	var avast PmgBoolean = PMGBOOLEAN__0
	this.Avast = &avast

	var clamav PmgBoolean = PMGBOOLEAN__1
	this.Clamav = &clamav

	var customCheck PmgBoolean = PMGBOOLEAN__0
	this.CustomCheck = &customCheck

	var customCheckPath string = "/usr/local/bin/pmg-custom-check"
	this.CustomCheckPath = &customCheckPath

	var dailyreport PmgBoolean = PMGBOOLEAN__1
	this.Dailyreport = &dailyreport


	var demo PmgBoolean = PMGBOOLEAN__0
	this.Demo = &demo


	var dkimUseDomain PmgConfigAdminDkimUseDomainEnum = PMGCONFIGADMINDKIMUSEDOMAINENUM_ENVELOPE
	this.DkimUseDomain = &dkimUseDomain


	var dkimSign PmgBoolean = PMGBOOLEAN__0
	this.DkimSign = &dkimSign

	var dkimSignAllMail PmgBoolean = PMGBOOLEAN__0
	this.DkimSignAllMail = &dkimSignAllMail

	var email string = "admin@domain.tld"
	this.Email = &email


	var statlifetime int64 = 7
	this.Statlifetime = &statlifetime

	return &this
}


// GetAdminMailFrom returns the AdminMailFrom field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAdminMailFrom() string {
	if o == nil || IsNil(o.AdminMailFrom) {
		var ret string
		return ret
	}
	return *o.AdminMailFrom
}

// GetAdminMailFromOk returns a tuple with the AdminMailFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAdminMailFromOk() (*string, bool) {
	if o == nil || IsNil(o.AdminMailFrom) {
		return nil, false
	}
	return o.AdminMailFrom, true
}

// HasAdminMailFrom returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasAdminMailFrom() bool {
	if o != nil && !IsNil(o.AdminMailFrom) {
		return true
	}

	return false
}

// SetAdminMailFrom gets a reference to the given string and assigns it to the AdminMailFrom field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetAdminMailFrom(v string) {
	o.AdminMailFrom = &v
}


// GetAdvfilter returns the Advfilter field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAdvfilter() PmgBoolean {
	if o == nil || IsNil(o.Advfilter) {
		var ret PmgBoolean
		return ret
	}
	return *o.Advfilter
}

// GetAdvfilterOk returns a tuple with the Advfilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAdvfilterOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Advfilter) {
		return nil, false
	}
	return o.Advfilter, true
}

// HasAdvfilter returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasAdvfilter() bool {
	if o != nil && !IsNil(o.Advfilter) {
		return true
	}

	return false
}

// SetAdvfilter gets a reference to the given PmgBoolean and assigns it to the Advfilter field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetAdvfilter(v PmgBoolean) {
	o.Advfilter = &v
}


// GetAvast returns the Avast field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAvast() PmgBoolean {
	if o == nil || IsNil(o.Avast) {
		var ret PmgBoolean
		return ret
	}
	return *o.Avast
}

// GetAvastOk returns a tuple with the Avast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetAvastOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Avast) {
		return nil, false
	}
	return o.Avast, true
}

// HasAvast returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasAvast() bool {
	if o != nil && !IsNil(o.Avast) {
		return true
	}

	return false
}

// SetAvast gets a reference to the given PmgBoolean and assigns it to the Avast field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetAvast(v PmgBoolean) {
	o.Avast = &v
}


// GetClamav returns the Clamav field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetClamav() PmgBoolean {
	if o == nil || IsNil(o.Clamav) {
		var ret PmgBoolean
		return ret
	}
	return *o.Clamav
}

// GetClamavOk returns a tuple with the Clamav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetClamavOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Clamav) {
		return nil, false
	}
	return o.Clamav, true
}

// HasClamav returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasClamav() bool {
	if o != nil && !IsNil(o.Clamav) {
		return true
	}

	return false
}

// SetClamav gets a reference to the given PmgBoolean and assigns it to the Clamav field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetClamav(v PmgBoolean) {
	o.Clamav = &v
}


// GetCustomCheck returns the CustomCheck field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetCustomCheck() PmgBoolean {
	if o == nil || IsNil(o.CustomCheck) {
		var ret PmgBoolean
		return ret
	}
	return *o.CustomCheck
}

// GetCustomCheckOk returns a tuple with the CustomCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetCustomCheckOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.CustomCheck) {
		return nil, false
	}
	return o.CustomCheck, true
}

// HasCustomCheck returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasCustomCheck() bool {
	if o != nil && !IsNil(o.CustomCheck) {
		return true
	}

	return false
}

// SetCustomCheck gets a reference to the given PmgBoolean and assigns it to the CustomCheck field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetCustomCheck(v PmgBoolean) {
	o.CustomCheck = &v
}


// GetCustomCheckPath returns the CustomCheckPath field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetCustomCheckPath() string {
	if o == nil || IsNil(o.CustomCheckPath) {
		var ret string
		return ret
	}
	return *o.CustomCheckPath
}

// GetCustomCheckPathOk returns a tuple with the CustomCheckPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetCustomCheckPathOk() (*string, bool) {
	if o == nil || IsNil(o.CustomCheckPath) {
		return nil, false
	}
	return o.CustomCheckPath, true
}

// HasCustomCheckPath returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasCustomCheckPath() bool {
	if o != nil && !IsNil(o.CustomCheckPath) {
		return true
	}

	return false
}

// SetCustomCheckPath gets a reference to the given string and assigns it to the CustomCheckPath field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetCustomCheckPath(v string) {
	o.CustomCheckPath = &v
}


// GetDailyreport returns the Dailyreport field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDailyreport() PmgBoolean {
	if o == nil || IsNil(o.Dailyreport) {
		var ret PmgBoolean
		return ret
	}
	return *o.Dailyreport
}

// GetDailyreportOk returns a tuple with the Dailyreport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDailyreportOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Dailyreport) {
		return nil, false
	}
	return o.Dailyreport, true
}

// HasDailyreport returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDailyreport() bool {
	if o != nil && !IsNil(o.Dailyreport) {
		return true
	}

	return false
}

// SetDailyreport gets a reference to the given PmgBoolean and assigns it to the Dailyreport field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDailyreport(v PmgBoolean) {
	o.Dailyreport = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDelete() string {
	if o == nil || IsNil(o.Delete) {
		var ret string
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDeleteOk() (*string, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given string and assigns it to the Delete field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDelete(v string) {
	o.Delete = &v
}


// GetDemo returns the Demo field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDemo() PmgBoolean {
	if o == nil || IsNil(o.Demo) {
		var ret PmgBoolean
		return ret
	}
	return *o.Demo
}

// GetDemoOk returns a tuple with the Demo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDemoOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.Demo) {
		return nil, false
	}
	return o.Demo, true
}

// HasDemo returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDemo() bool {
	if o != nil && !IsNil(o.Demo) {
		return true
	}

	return false
}

// SetDemo gets a reference to the given PmgBoolean and assigns it to the Demo field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDemo(v PmgBoolean) {
	o.Demo = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetDkimUseDomain returns the DkimUseDomain field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimUseDomain() PmgConfigAdminDkimUseDomainEnum {
	if o == nil || IsNil(o.DkimUseDomain) {
		var ret PmgConfigAdminDkimUseDomainEnum
		return ret
	}
	return *o.DkimUseDomain
}

// GetDkimUseDomainOk returns a tuple with the DkimUseDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimUseDomainOk() (*PmgConfigAdminDkimUseDomainEnum, bool) {
	if o == nil || IsNil(o.DkimUseDomain) {
		return nil, false
	}
	return o.DkimUseDomain, true
}

// HasDkimUseDomain returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDkimUseDomain() bool {
	if o != nil && !IsNil(o.DkimUseDomain) {
		return true
	}

	return false
}

// SetDkimUseDomain gets a reference to the given PmgConfigAdminDkimUseDomainEnum and assigns it to the DkimUseDomain field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDkimUseDomain(v PmgConfigAdminDkimUseDomainEnum) {
	o.DkimUseDomain = &v
}


// GetDkimSelector returns the DkimSelector field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSelector() string {
	if o == nil || IsNil(o.DkimSelector) {
		var ret string
		return ret
	}
	return *o.DkimSelector
}

// GetDkimSelectorOk returns a tuple with the DkimSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSelectorOk() (*string, bool) {
	if o == nil || IsNil(o.DkimSelector) {
		return nil, false
	}
	return o.DkimSelector, true
}

// HasDkimSelector returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDkimSelector() bool {
	if o != nil && !IsNil(o.DkimSelector) {
		return true
	}

	return false
}

// SetDkimSelector gets a reference to the given string and assigns it to the DkimSelector field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDkimSelector(v string) {
	o.DkimSelector = &v
}


// GetDkimSign returns the DkimSign field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSign() PmgBoolean {
	if o == nil || IsNil(o.DkimSign) {
		var ret PmgBoolean
		return ret
	}
	return *o.DkimSign
}

// GetDkimSignOk returns a tuple with the DkimSign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSignOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.DkimSign) {
		return nil, false
	}
	return o.DkimSign, true
}

// HasDkimSign returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDkimSign() bool {
	if o != nil && !IsNil(o.DkimSign) {
		return true
	}

	return false
}

// SetDkimSign gets a reference to the given PmgBoolean and assigns it to the DkimSign field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDkimSign(v PmgBoolean) {
	o.DkimSign = &v
}


// GetDkimSignAllMail returns the DkimSignAllMail field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSignAllMail() PmgBoolean {
	if o == nil || IsNil(o.DkimSignAllMail) {
		var ret PmgBoolean
		return ret
	}
	return *o.DkimSignAllMail
}

// GetDkimSignAllMailOk returns a tuple with the DkimSignAllMail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetDkimSignAllMailOk() (*PmgBoolean, bool) {
	if o == nil || IsNil(o.DkimSignAllMail) {
		return nil, false
	}
	return o.DkimSignAllMail, true
}

// HasDkimSignAllMail returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasDkimSignAllMail() bool {
	if o != nil && !IsNil(o.DkimSignAllMail) {
		return true
	}

	return false
}

// SetDkimSignAllMail gets a reference to the given PmgBoolean and assigns it to the DkimSignAllMail field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetDkimSignAllMail(v PmgBoolean) {
	o.DkimSignAllMail = &v
}


// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetEmail(v string) {
	o.Email = &v
}


// GetHttpProxy returns the HttpProxy field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetHttpProxy() string {
	if o == nil || IsNil(o.HttpProxy) {
		var ret string
		return ret
	}
	return *o.HttpProxy
}

// GetHttpProxyOk returns a tuple with the HttpProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetHttpProxyOk() (*string, bool) {
	if o == nil || IsNil(o.HttpProxy) {
		return nil, false
	}
	return o.HttpProxy, true
}

// HasHttpProxy returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasHttpProxy() bool {
	if o != nil && !IsNil(o.HttpProxy) {
		return true
	}

	return false
}

// SetHttpProxy gets a reference to the given string and assigns it to the HttpProxy field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetHttpProxy(v string) {
	o.HttpProxy = &v
}


// GetStatlifetime returns the Statlifetime field value if set, zero value otherwise.
func (o *ConfigAdminUpdateAdminSectionRequest) GetStatlifetime() int64 {
	if o == nil || IsNil(o.Statlifetime) {
		var ret int64
		return ret
	}
	return *o.Statlifetime
}

// GetStatlifetimeOk returns a tuple with the Statlifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) GetStatlifetimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Statlifetime) {
		return nil, false
	}
	return o.Statlifetime, true
}

// HasStatlifetime returns a boolean if a field has been set.
func (o *ConfigAdminUpdateAdminSectionRequest) HasStatlifetime() bool {
	if o != nil && !IsNil(o.Statlifetime) {
		return true
	}

	return false
}

// SetStatlifetime gets a reference to the given int64 and assigns it to the Statlifetime field.
func (o *ConfigAdminUpdateAdminSectionRequest) SetStatlifetime(v int64) {
	o.Statlifetime = &v
}


func (o ConfigAdminUpdateAdminSectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAdminUpdateAdminSectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.AdminMailFrom) {
		toSerialize["admin-mail-from"] = o.AdminMailFrom
	}
	
	if !IsNil(o.Advfilter) {
		toSerialize["advfilter"] = o.Advfilter
	}
	
	if !IsNil(o.Avast) {
		toSerialize["avast"] = o.Avast
	}
	
	if !IsNil(o.Clamav) {
		toSerialize["clamav"] = o.Clamav
	}
	
	if !IsNil(o.CustomCheck) {
		toSerialize["custom_check"] = o.CustomCheck
	}
	
	if !IsNil(o.CustomCheckPath) {
		toSerialize["custom_check_path"] = o.CustomCheckPath
	}
	
	if !IsNil(o.Dailyreport) {
		toSerialize["dailyreport"] = o.Dailyreport
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Demo) {
		toSerialize["demo"] = o.Demo
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.DkimUseDomain) {
		toSerialize["dkim-use-domain"] = o.DkimUseDomain
	}
	
	if !IsNil(o.DkimSelector) {
		toSerialize["dkim_selector"] = o.DkimSelector
	}
	
	if !IsNil(o.DkimSign) {
		toSerialize["dkim_sign"] = o.DkimSign
	}
	
	if !IsNil(o.DkimSignAllMail) {
		toSerialize["dkim_sign_all_mail"] = o.DkimSignAllMail
	}
	
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	
	if !IsNil(o.HttpProxy) {
		toSerialize["http_proxy"] = o.HttpProxy
	}
	
	if !IsNil(o.Statlifetime) {
		toSerialize["statlifetime"] = o.Statlifetime
	}
	
	return toSerialize, nil
}

type NullableConfigAdminUpdateAdminSectionRequest struct {
	value *ConfigAdminUpdateAdminSectionRequest
	isSet bool
}

func (v NullableConfigAdminUpdateAdminSectionRequest) Get() *ConfigAdminUpdateAdminSectionRequest {
	return v.value
}

func (v *NullableConfigAdminUpdateAdminSectionRequest) Set(val *ConfigAdminUpdateAdminSectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAdminUpdateAdminSectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAdminUpdateAdminSectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAdminUpdateAdminSectionRequest(val *ConfigAdminUpdateAdminSectionRequest) *NullableConfigAdminUpdateAdminSectionRequest {
	return &NullableConfigAdminUpdateAdminSectionRequest{value: val, isSet: true}
}

func (v NullableConfigAdminUpdateAdminSectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAdminUpdateAdminSectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


